### ISSUE TITLE
Image for README.md

### ISSUE THREAD

**Issue by melezov** [ngs-doo/dsl-json#1]
This image will be referenced in the README.md:

![JVM serializers benchmark results](https://cloud.githubusercontent.com/assets/551485/11827913/227130e4-a390-11e5-87eb-939c14db938f.png)

**Comment by melezov** [comment]
Bolded dsl-platform results:

![jvm-serializers-results](https://cloud.githubusercontent.com/assets/551485/11828210/07a3ecfe-a393-11e5-8d5e-45bdb68f014b.png)

**Comment by zapov** [comment]
![chart](https://cloud.githubusercontent.com/assets/1181401/13662269/8c49a02c-e699-11e5-9e46-f98f07fd68ef.png)
