### ISSUE TITLE
Unable to find reader/writer for wildcard types

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#101]
If we try to deserialize json using following type:
```
new TypeDefinition<MyGeneric<Map<String, ? extends String>>>() {}.type
```
We got error:
```
com.dslplatform.json.SerializationException: Unable to find reader for ? extends java.lang.String. Enable runtime conversion by initializing DslJson with new DslJson<>(Settings.withRuntime().includeServiceLoader())
```

I've discovered this issue while working with Kotlin. 
Since in Kotlin the Map is defined as `interface Map<K, out V>`, when you create parameterized type `Map<String, String>` actually it will be `Map<String, ? extends String>`.

**Comment by ma1uta** [comment]
String is a final class, there is no way to inherits from the String. The expression `? extends String` doesn't make sense.

**Comment by zapov** [comment]
I remember seeing that in Kotlin.
I dealt with it via compatible type comparison: https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/processor/Analysis.java#L1580

**Comment by varahash** [comment]
@ma1uta This is just example, it doesn't matter what type is used. The main point is that, when you write in Kotlin following code:
`val type = object : TypeDefenition<Map<String, Number>>(){}.type`
it will be compiled to following java equivalent: 
`Type type = new TypeDefenition<Map<String, ? extends Number>>(){}.type;`.
This happens due to [Declaration-site variance](https://kotlinlang.org/docs/reference/generics.html#declaration-site-variance) in Kotlin.

@zapov We should correctly process WildcardType inside tryFind*() methods to fix this issue.

**Comment by zapov** [comment]
Yes, we should. Do you want to take care of that?

**Comment by ma1uta** [comment]
Ok, I see you.

**Comment by zapov** [comment]
I've added some support for it here: https://github.com/ngs-doo/dsl-json/commit/4ab76bbb5478d4516b77829b3808128f517af26c
