### ISSUE TITLE
[Documentation] Please add simple json string parsing example to Readme.md

### ISSUE THREAD

**Issue by jleaders** [ngs-doo/dsl-json#104]
One of the most common use-cases of JSON libraries is taking a string and parsing it to a JSON array object of some sort, but I notice dsl-json's Readme.md has plenty of information about the library but no "common case" string serialization example at the top level. Please add.
Something equivalent to javascripts
`var obj = JSON.parse('{ "name":"John", "age":30, "city":"New York"}');`
Thank you.

**Comment by zapov** [comment]
The main reason why there are no string parsing examples in the readme is that parsing JSON from string is a bad practice.
It's discouraged to do so, and doubly discouraged to do so in DSL-JSON which doesn't have a String friendly API.
If you look closely you will actually find it here:

    byte[] bytes = "{\"number\":123}".getBytes("UTF-8");
    JsonReader<Object> reader = json.newReader().process(bytes, bytes.length);

But in a sense you are right. Even if its discouraged to do that, that fact is strange to most developers, and there should probably be a section in the readme about it. Even with the example of how to do it if you really need to (as the one above).

I'll add it soon

**Comment by zapov** [comment]
There is now section about String API in readme. Let me know if that explains things and resolves the issue

**Comment by jleaders** [comment]
That works. I presume it's discouraged for performance reasons, so this is kind of a "binary" JSON library it sounds like. Its good to have that clear in the Readme.
