### ISSUE TITLE
@JsonAttribute ignored on non-public fields

### ISSUE THREAD

**Issue by codeaze** [ngs-doo/dsl-json#106]
I'm trying to use dsl-json in combination with objectbox. In object-box relations are made setting fields ToOne/ToMany, which do not have default constructors, so not serializable by dsl-json directly. As a workaround, I'm setting these fields to private/protected and serialize/deserialize through getters/setters. But then the problem is that @JsonAttribute (ignore, alternative names) is not usable anymore.

**Comment by zapov** [comment]
Library supports all kind of construction patterns (factories, builder, ctor with arguments).
Analysis will only inspect the relevant fields like ctors, getters, setters and factories... so it's expected that ignores private fields.
What is your actual class definition? Can you put annotations on relevant parts?

**Comment by codeaze** [comment]
Well, I've resolved it already by adding @JsonAttribute annotation on getter/setter of the field. It works now well. 

I think it is worth mentioning (somewhere in the README) that only public elements will be handled by the Annotation Processor, so if you have a non-public fields, put your annotations on public getters/setters instead. 

Also another interesting moment is that non-public fields with public get/set that start with a capital letter are not handled properly. For example: 

```
private Document DOC;

public Document getDOC() {
    return DOC;
}

public void setDOC(DOC doc) {
    DOC = doc;
}

```

it won't deserialize string like `"DOC": { ... }`, instead it expects `"dOC": { ... }`

**Comment by zapov** [comment]
Putting annotation on private field should produce warning as it's not going to get picked up for analysis.
And yes, I'm sure the library does not follow bean naming to the letter.
Both of those are worth fixing (or at least improving)

**Comment by zapov** [comment]
Both of this issues are resolved in next version
