### ISSUE TITLE
Scala example doesn't compile

### ISSUE THREAD

**Issue by VasilySizov** [ngs-doo/dsl-json#112]
Hi! It looks like the Scala example per the link below doesn't work (it says dslJson doesn't have ecode/decode methods):
https://github.com/ngs-doo/dsl-json/blob/master/examples/Scala/src/main/scala/com/dslplatform/json/example/Example.scala

I believe it is lacking instantiation of the DslJsonScala, e.g. in bold below: 
  implicit val dslJson = new DslJson[Any]()
  **val dslJsonScala = new DslJsonScala(dslJson)**

and using dsjJsonScala everywhere below.

**Comment by zapov** [comment]
Project works for me from IDEA or by running sbt run

How do you run it?
It sounds like implicits are not working when you try to compile.
You can certainly use DslJsonScala signature, but I'm not sure how to replicate your problem ;(

**Comment by VasilySizov** [comment]
Hm... tried to isolate, and it seems like it is an issue with IDEA, not with the code. It runs, but the code highlighting shows errors:
![issue2](https://user-images.githubusercontent.com/3389718/52044126-374f2800-24f6-11e9-9bad-a59ad357915f.png)

**Comment by zapov** [comment]
So I guess I can close this?
