### ISSUE TITLE
Do not serialize empty collections

### ISSUE THREAD

**Issue by RoKish** [ngs-doo/dsl-json#115]
Is there a way to not serialize empty collections? I see that the default values are omitted if `skipDefaultValues` is `true`, but there's no way to define default values for serialization as it's happening in compile time. Also I cannot define custom `ConverterFactory` because some collections are serialized using `JsonWriter#serialize`, which I cannot override somehow because it's created by `DslJson`.

**Comment by zapov** [comment]
This will work as expected in Java8 version for 1.9.0
I added that missing feature recently (it was working like that for DSL version)

As a temp workaround you can attach custom converter for that property and control it that way.

**Comment by zapov** [comment]
v1.9.0 released
Collections should be serialized as expected now. There is also relevant test here: https://github.com/ngs-doo/dsl-json/blob/c4486e8d29b425272212565bee49d1d814f0ffd6/tests-java8/src/test/java/com/dslplatform/json/ObjectFormatPolicyTest.java#L79
