### ISSUE TITLE
Release for Scala 2.13

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#119]
```
[error] unresolved dependency: com.dslplatform#dsl-json-scala_2.13.0-M5;1.8.5: not found
```

**Comment by zapov** [comment]
Yeah ;( I don't usually bother releasing libs for non GA versions.

There are only so many hours in a day ;(
You offered to help previously. Is that still a thing? I did not hear anything back on the Scala code gen issue

**Comment by plokhotnyuk** [comment]
I cannot build a Scala module of DSL-JSON, here is an error:
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-pgp;0.8.3: not found
```

Steps to reproduce:
1. Clone repo: `git clone git@github.com:ngs-doo/dsl-json.git`
2. Enter the root dir: `cd dsl-json`
3. Replace `1.9.0` by `1.9.0-SNAPSHOT` using the following command: `grep -rlZ 1.9.0 . --exclude-dir=.git | xargs -0 sed -i 's/1\.9\.0/1.9.0-SNAPSHOT/g'`
4. Build Java modules: `mvn clean install`
5. Enter into the `scala` directory: `cd scala`
6. Try to build and publish the Scala module: `sbt clean +publishLocal`

**Comment by zapov** [comment]
Ah the joy of "stable builds" :D

In the plugins.sbt comment out the addSbtPlugin line
In the build.sbt comment out useGpg line

They are only needed for +publishSigned [and newer version does not work ;( ]

**Comment by plokhotnyuk** [comment]
Scala 2.13.0-RC1 is already available: https://github.com/scala/scala/releases/tag/v2.13.0-RC1

**Comment by zapov** [comment]
I tried adding support for `2.13.0-RC1` but not all dependencies support that ;(

eg: `org.specs2#specs2-scalacheck_2.13.0-RC1;4.5.1` does not exists

Any advice?

**Comment by plokhotnyuk** [comment]
Yeah, need to wait until maintainers cut a version for this binary incompatible release: https://github.com/etorreborre/specs2/issues/735

**Comment by plokhotnyuk** [comment]
specs2 is cut and already available on the Maven Central: https://repo1.maven.org/maven2/org/specs2/specs2-scalacheck_2.13.0-RC1/

**Comment by zapov** [comment]
I've released a 1.9.2 for 2.13
I need to fix some code before I push since it does not compile on all version ;(

**Comment by plokhotnyuk** [comment]
Nice! 

Here is place where all libs and their versions for RC1 are listed: https://github.com/scala/make-release-notes/blob/2.13.x/projects-2.13.md

**Comment by plokhotnyuk** [comment]
up

**Comment by zapov** [comment]
:tada:

**Comment by plokhotnyuk** [comment]
I hope it in the way to the Maven Central, but please recheck because no new releases are available on the staging repo too:
https://oss.sonatype.org/content/repositories/staging/com/dslplatform/

**Comment by zapov** [comment]
Damn. I was certain I clicked release button in Sonatype yesterday ;(
I re-released it again now :)
