### ISSUE TITLE
Feature Request: Register Interfaces on ExternalSerialization#setup

### ISSUE THREAD

**Issue by jamespedwards42** [ngs-doo/dsl-json#12]
For `@CompiledJson` classes, would it be possible to register generated JsonReader/Writers with the interface they implement as well?  The behavior I am observing is that only the annotated class is registered (`DslJson#registerReader`).  Maybe adding a list of superclasses to the @CompiledJson annotation would be the easiest route?

Currently, I have an [if statement for each expected interface and then manually pass the corresponding implementation class.](https://github.com/jamespedwards42/bitnodes-java-client/blob/master/dslplatform-data/src/com.fabahaba.bitnodes_dslplatform_data/java/com/fabahaba/bitnodes/BitnodesDecoder.java#L39)

**Comment by zapov** [comment]
Writers are already looked up through their inheritance chain.
Readers are not since they go in separate direction.

I suppose you don't want to register it manually through: https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/DslJson.java#L271 to avoid referencing generated code?
I guess baseReaders (or something like that) makes sense on CompiledJson.

**Comment by jamespedwards42** [comment]
Exactly, trying to avoid any maintenance or breakage from every time a new ExternalSerialization is generated.

**Comment by zapov** [comment]
I've added some initial implementation. Let me know if you find any issues, have any comments.

**Comment by jamespedwards42** [comment]
[Works perfectly](https://github.com/jamespedwards42/bitnodes-java-client/commit/63b89d55f8876fe44d4de196690e5342f3ad8f34), thank you!!!

**Comment by zapov** [comment]
btw. I realized that you can get the same behavior with something along the lines of

    dsljson.registerReader(interface.class, dsljson.tryFindReader(implementation.class))

but tryFindReader is protected :(

**Comment by jamespedwards42** [comment]
I think I like that even better :), feels more flexible and avoids conflicts.  That way you don't end up enforcing a reader/implementation for a given Interface for every `DslJson` that is constructed.

**Comment by zapov** [comment]
So you are fine with me removing that baseReaders feature?

I guess I should make tryFindReader/tryFindWriter public :/

**Comment by jamespedwards42** [comment]
I happy with either or both.  Why are you against making tryFind* public?

**Comment by zapov** [comment]
I'm not :)
protected is almost the same as public :D

I guess the reason I didn't make them public initially is because of dualism, since getObjectReader should be public then.
And people might get confused with that. I guess I'll leave that protected, but will make try public

**Comment by zapov** [comment]
tryFind methods are now public

**Comment by jamespedwards42** [comment]
Is there a public snapshot maven repository available to test out these changes?

**Comment by zapov** [comment]
For some reason I dont have a habit od -snapshot. If you make a pr with all the required pom changes I can release a snapshot version on Maven (never did so yet). If you just want to test it, you can subclass and test

**Comment by jamespedwards42** [comment]
Sorry, I can't be of any help there, I'm completely lost in the maven world, Gradle converted me a while ago.  I have been able to confirm it works by simply building locally.  Really just wanted to release a library that depends on that feature.

**Comment by zapov** [comment]
Why not subclass as temp solution?

    class MyDslJson extends DslJson

**Comment by jamespedwards42** [comment]
I just didn't want to go back and change anything later.  Any plans for a release?

**Comment by zapov** [comment]
I'll look into releasing it over the weekend
