### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException during serialization of Array[Double]

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#120]
Code to reproduce:
```
val writer = new DslJsonScala(new DslJson[Any]()).json.newWriter()
NumberConverter.DOUBLE_ARRAY_WRITER.write(writer, Array[Double](-2.3550447074000003E-5))
```

**Comment by plokhotnyuk** [comment]
BTW, would you like to revise implementation of serialization for doubles and floats and port the [Ryū routines](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1589-L1930) to Java?

It can produce shorter output without loosing in precision and outperform both: the standard Java's toString (that is used by Jackson) and Grusu3:
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                                           (size)   Mode  Cnt       Score       Error  Units
[info] ArrayOfDoublesBenchmark.writeDslJsonScala               40  thrpt    5  202703.795 ± 23330.519  ops/s
[info] ArrayOfDoublesBenchmark.writeJacksonScala               40  thrpt    5  113831.206 ±   449.500  ops/s
[info] ArrayOfDoublesBenchmark.writeJsoniterScala              40  thrpt    5  358323.652 ±  4401.615  ops/s
```

**Comment by zapov** [comment]
I'm a bit swamped right now.... so can't really dig into the problem ;(
But it would be great if double/float encoding/decoding were bug free :)

If you want to invest some time to port it to DSL-JSON that would be great.

**Comment by zapov** [comment]
btw. if you don't have time I might find some time next month for that, but certainly not for v1.9.0

**Comment by zapov** [comment]
Fixed in latest commit: https://github.com/ngs-doo/dsl-json/commit/e0dfb2dcbf209a0114de1a4cfe7115d8dfd7c5d5
I'll close this and open up a separate issue for float/double refactoring
