### ISSUE TITLE
Safe and efficient parsing of `BigInteger` and `BigDecimal` values wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#124]
Currently big numbers in Java has a binary representation under hood, and parsing them from the decimal string representation has `O(n^2)` complexity.

```
scala> def timed[A](f: => A): A = { val t = System.currentTimeMillis; val r = f; println(s"Elapsed time (ms): ${System.currentTimeMillis - t}"); r }
timed: [A](f: => A)A

scala> timed(new java.math.BigInteger("9" * 100000))
Elapsed time (ms): 142

scala> timed(new java.math.BigInteger("9" * 1000000))
Elapsed time (ms): 13151

cala> timed(new java.math.BigDecimal("9" * 100000))
Elapsed time (ms): 140

scala> timed(new java.math.BigDecimal("9" * 1000000))
Elapsed time (ms): 13165
```

For current 1Gb network 10ms of receiving a malicious message with a 1M digit number can produce 1300ms of 100% CPU load in a one core. More than 100 cores can be effectively DoS-ed at a full bandwidth rate.

Also, lot of arithmetic operations has O(n^1.5) complexity, even such a "safe" operations as `+` for not validated scale of input can DoS much more efficiently by a single message with a 12-digit number:

```
scala> timed(new java.math.BigDecimal("1e-100000000"))
Elapsed time (ms): 0

scala> timed((new java.math.BigDecimal("1e-100000000")).add(java.math.BigDecimal.ONE))
Elapsed time (ms): 91591
```

1) Need to check length of mantissa before parsing and scale (for `BigDecimal`) after to save users from such kind of attacks.
2) Use more efficient routines for parsing which has `O(n^1.5)` complexity, like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/0702be944a72010b4ca7339e0b786e86381d928d/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1477-L1589).

**Comment by zapov** [comment]
There is a partial guard for that with check for number of digits around the code.
But I think I added full guard for that only yesterday (in prepareBuffer)

**Comment by plokhotnyuk** [comment]
Can these limit be configured?

**Comment by zapov** [comment]
Yes: https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/DslJson.java#L388

**Comment by plokhotnyuk** [comment]
What about of adding an ability to configure a math context (for rounding of the mantissa after parsing) and a limit for scale (to avoid DoS due malicious input)?

**Comment by zapov** [comment]
More configs should be fine, there are probably a lot of useful missing configurations.

**Comment by plokhotnyuk** [comment]
I see that for `BigInt` values there no pre-configured limits in DSL-JSON, and the following benchmark do not need any configuration to parse 1M digit numbers (limits for number of digits are applied only for `BigDecimal` values):

https://github.com/plokhotnyuk/jsoniter-scala/blob/311415bc243ff85450978f2da54de3758acda1ce/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/BigIntBenchmark.scala#L39-L40

BTW, here are results of benchmarks for parsing of `BigInt` values for different sizes:
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                           (size)   Mode  Cnt         Score         Error  Units
[info] BigIntBenchmark.readDslJsonScala         1  thrpt    5  62472145.721 ± 3590966.859  ops/s
[info] BigIntBenchmark.readDslJsonScala        10  thrpt    5  28368536.446 ±  401335.381  ops/s
[info] BigIntBenchmark.readDslJsonScala       100  thrpt    5   1572789.745 ±  124580.589  ops/s
[info] BigIntBenchmark.readDslJsonScala      1000  thrpt    5     60353.280 ±     391.091  ops/s
[info] BigIntBenchmark.readDslJsonScala     10000  thrpt    5       721.307 ±       6.251  ops/s
[info] BigIntBenchmark.readDslJsonScala    100000  thrpt    5         7.716 ±       0.225  ops/s
[info] BigIntBenchmark.readDslJsonScala   1000000  thrpt    5         0.076 ±       0.002  ops/s
[info] BigIntBenchmark.readJsoniterScala        1  thrpt    5  63231733.279 ± 1776036.149  ops/s
[info] BigIntBenchmark.readJsoniterScala       10  thrpt    5  29058710.636 ± 2183302.893  ops/s
[info] BigIntBenchmark.readJsoniterScala      100  thrpt    5   3828647.059 ±   45481.212  ops/s
[info] BigIntBenchmark.readJsoniterScala     1000  thrpt    5    185322.923 ±   12034.895  ops/s
[info] BigIntBenchmark.readJsoniterScala    10000  thrpt    5      4730.329 ±     296.480  ops/s
[info] BigIntBenchmark.readJsoniterScala   100000  thrpt    5       121.504 ±       5.098  ops/s
[info] BigIntBenchmark.readJsoniterScala  1000000  thrpt    5         3.492 ±       0.287  ops/s
```

**Comment by zapov** [comment]
The v1.9.1 includes the guard on BigInt

**Comment by zapov** [comment]
Guards are there. I have no plans to optimize built-in converters. One can always override them if they need more performance.
