### ISSUE TITLE
Strings are not nullable

### ISSUE THREAD

**Issue by codeaze** [ngs-doo/dsl-json#125]
Since upgrading from 1.8.5 to 1.9.x deserialization does not work for me anymore. String values that can be nullable are not deserialized correctly, namely DSL-JSON throws an exception that double quotes expected for string ("null" instead of null?).

I've checked generated files, and for all string properties we have `StringConverter.deserialize(...)`. Shouldn't it be instead `StringConverter.deserializeNullable(...)` ?

I've also looked through commits from 1.8.5 up to 1.9.0, and I guess that the change resulted in current situation is here: https://github.com/ngs-doo/dsl-json/commit/aaa83c11203dd47e2a721e8f08785a53eebd6cd7. But I might be wrong.

Please advice what to do. Thanks.

**Comment by zapov** [comment]
Tnx for the bug report. I've fixed it in latest commit: https://github.com/ngs-doo/dsl-json/commit/b4e3e4644d9183333b53d43197a9e05c0585c48a

I'll release new version later today.

**Comment by zapov** [comment]
Version 1.9.2 released

**Comment by codeaze** [comment]
Is there a chance that a similar case we also have for `Long`?

**Comment by zapov** [comment]
It seems so ;(
I'll fix it shortly

**Comment by codeaze** [comment]
Aren't there any JUnit tests available to check such cases?

**Comment by zapov** [comment]
v1.9.3 released :tired_face:

**Comment by zapov** [comment]
I hope everything is working as expected now

**Comment by codeaze** [comment]
Thanks for the effort. 
There might be a different case, which I haven't checked throughly yet. I get exception while trying to deserialize json for classes not annotated with `@CompiledJson`. Once I put the annotation, everything works fine.
