### ISSUE TITLE
java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#127]
Code to reproduce:
```
import com.dslplatform.json.{DslJson, DslJsonScala}

case class V(
              text: String,
              value: Int)

case class ES(
               distance: V,
               duration: V,
               status: String)

case class RS(elements: IndexedSeq[ES])

case class DM(
               destination_addresses: IndexedSeq[String],
               origin_addresses: IndexedSeq[String],
               rows: IndexedSeq[RS],
               status: String)


val dslJson = new DslJson[Any](Settings.withRuntime().`with`(new ConfigureScala))
val dslJsonScala = new DslJsonScala(dslJson)
val decoder = dslJsonScala.decoder[DM]
val reader = dslJson.newReader()
val bytes = "{\"destination_addresses\":[],\"origin_addresses\":[],\"rows\":[],\"status\":\"OK\"}".getBytes
reader.process(bytes, bytes.length)
reader.read()
println(decoder.read(reader))
```

**Comment by zapov** [comment]
I'm unable to reproduce this ;(

I pasted your code as is into the Scala example at: https://github.com/ngs-doo/dsl-json/blob/master/examples/Scala/src/main/scala/com/dslplatform/json/example/Example.scala and test, but it worked both times.

Which Java/Scala versions are you using?

**Comment by plokhotnyuk** [comment]
I think it doesn't not depend on Java/Scala version... Just need to uncomment [this](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/GoogleMapsAPIBenchmarkSpec.scala#L11) line, it's implementation [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/GoogleMapsAPIBenchmark.scala#L32-L35), and run the test.

Top of the stack trace:
```
argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.dslplatform.json.runtime.ScalaClassAnalyzer$$anon$1.apply(ScalaClassAnalyzer.scala:318)
	at com.dslplatform.json.runtime.ScalaClassAnalyzer$$anon$1.apply(ScalaClassAnalyzer.scala:317)
	at com.dslplatform.json.runtime.ImmutableDescription.finalChecks(ImmutableDescription.java:147)
	at com.dslplatform.json.runtime.ImmutableDescription.read(ImmutableDescription.java:87)
	at com.dslplatform.json.runtime.ArrayBufferDecoder.read(ArrayBufferDecoder.scala:24)
	at com.dslplatform.json.runtime.ArrayBufferDecoder.read(ArrayBufferDecoder.scala:8)
	at com.dslplatform.json.runtime.ScalaClassAnalyzer$WriteCtor.read(ScalaClassAnalyzer.scala:407)
	at com.dslplatform.json.runtime.ImmutableDescription.read(ImmutableDescription.java:82)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.DslPlatformJson$.dslJsonDecode(DslPlatformJson.scala:57)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.GoogleMapsAPIBenchmark.readDslJsonScala(GoogleMapsAPIBenchmark.scala:34)
	at com.github.plokhotnyuk.jsoniter_scala.benchmark.GoogleMapsAPIBenchmarkSpec.$anonfun$new$2(GoogleMapsAPIBenchmarkSpec.scala:10)
```

**Comment by zapov** [comment]
I see that it complains about argument signature (ArrayBuffer vs IndexedSeq)
but I was unable to reproduce the issue locally ;(

It should work now in your benchmark with latest commit: https://github.com/ngs-doo/dsl-json/commit/8b744809d6754d75aecd38a439ce4da715ca1f37

**Comment by plokhotnyuk** [comment]
May it be due [this workaround](dslJson.encoder[T]) which was required to get encoder for `Array[Boolean]`?

**Comment by zapov** [comment]
The link is not working, but I figured out that it was not working because the failing test was using immutable.IndexedSeq while just IndexedSeq works.
I was not aware of this problem with array of primitives, fixed it now.

Released a new version, hopefully everything should work now :)

**Comment by plokhotnyuk** [comment]
Thanks a lot!

I have removed [that "workaround"](https://github.com/plokhotnyuk/jsoniter-scala/commit/cb5cbc80aae3eeb43356f4d96d34adabd3015949) and now the benchmark for Google Maps API parse `DistanceMatrix` without errors. 

But the same exception throws now in the [`TwitterAPIBenchmark.readDslJsonScala`](https://github.com/plokhotnyuk/jsoniter-scala/blob/cb5cbc80aae3eeb43356f4d96d34adabd3015949/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/TwitterAPIBenchmark.scala#L33) benchmark.

**Comment by zapov** [comment]
:(
I added support for immutable Seq

Also I see that it's "failing" on the write test due to encoding empty collections. You can avoid that by using `.skipDefaultValues(true)` during config, but this will also omit other default properties, such as Boolean and other primitives.

**Comment by zapov** [comment]
Actually no, this does not work yet in Scala ;(

**Comment by zapov** [comment]
v1.9.3 released

**Comment by plokhotnyuk** [comment]
Thank you! I will try it tomorrow.

BTW, what do you think about merging of Java and Scala projects to the one multi-project with the same version, and setting up a release automation by the git tag?

[Here](https://github.com/hseeberger/akka-http-json/pull/243) is an example how it can be done by sbt. Possible it is also can be automated by gradle or maven plugins ...

**Comment by zapov** [comment]
Yes, that would be nice but it would need to be Maven instead of SBT ;(
While SBT is much more powerful, it's foreign to most Java devs.

I didn't want to invest time in looking up how to setup Scala project with Maven ;( But I would prefer it was setup that way.

**Comment by plokhotnyuk** [comment]
I have tested with v1.9.3 

No more `java.lang.IllegalArgumentException: argument type mismatch`.
