### ISSUE TITLE
Support of rest java.time.* values wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#131]
Currently DSL-JSON supports only: `LocalDate`, `LocalDateTime`, `OffsetDateTime`, partially `ZonedDateTime` (without optional timezones, see #130), `Month` and `DayOfWeek` as Java enums

Wanted support of ISO-8601 representation (with IANA timezones) for:
`LocalTime`
`Instant`
`OffsetTime`
`ZoneOffset`
`ZoneId`
`Year`
`YearMoth`
`MonthDay`

**Comment by zapov** [comment]
Some of this is useful, such as LocalTime and maybe OffsetTime
Not sure about the others.
I have never used them as data types for APIs so it's hard for me to see when could they be useful.
Do you have some use case example?

**Comment by master-bytes-krafter** [comment]
I need to check what is causing these large diffs, thought it was line feed but it is propably something else

**Comment by zapov** [comment]
Most relevant types are now in base library. Others can be registered as any other custom type
