### ISSUE TITLE
Settings.withRuntime() not exists 

### ISSUE THREAD

**Issue by mmaryo** [ngs-doo/dsl-json#135]
Hello 

I'm unable to find Settings.withRuntime() with last version 1.9.3

![Screenshot 2019-05-08 19:28:27](https://user-images.githubusercontent.com/1669985/57395083-7c56ba80-71c7-11e9-8805-cef3a4bc3960.png)

Is withRuntime() removed ?

**Comment by zapov** [comment]
It's from java8 dependency in the runtime namespace: https://github.com/ngs-doo/dsl-json/blob/master/java8/src/main/java/com/dslplatform/json/runtime/Settings.java
