### ISSUE TITLE
Incorrect condition in Analysis for verification of custom converter

### ISSUE THREAD

**Issue by master-bytes-krafter** [ngs-doo/dsl-json#138]
Hello, 
i found an issue in Analysis.java for custom converter existence verification

`else if (jsonReaderField == null && jsonReaderMethod == null || jsonWriterField == null && jsonWriterMethod == null) `

Should be 
`else if ((jsonReaderField == null || jsonReaderMethod == null) && (jsonWriterField == null || jsonWriterMethod == null)) {`
Otherwise it evaluates wrong.

Can i make/submit a PR so that it can be merged (and hopefully released) quickly (it blocks our build right now, we need to make a workaround) :)
Regards

**Comment by zapov** [comment]
Hi,

yes you can make PR. Just please include a test which fails with the current code but works with your fix.

**Comment by master-bytes-krafter** [comment]
Hello, sorry for the delay, will be working on it soon

**Comment by master-bytes-krafter** [comment]
Before i create the PR, can you confirm that for a converter READ AND WRITE are mandatory or it may only provide READ OR WRITE, if it is the former then the error message is misleading, if it is the later then i will create the PR

**Comment by zapov** [comment]
It must have both. But I didn't bother separating checks and pointing out which one is currently missing, so thus the `or` in the message.
If you want to make a better error message, or split the check, sure

**Comment by master-bytes-krafter** [comment]
Ok if it must have both it changes everything ;) a more explicit error message will suffice

**Comment by master-bytes-krafter** [comment]
#140

**Comment by zapov** [comment]
v1.10 released which has better error messages for this case
