### ISSUE TITLE
empty map deserialize error

### ISSUE THREAD

**Issue by yueyijingque** [ngs-doo/dsl-json#139]
When I deserialize something like the code below, it throws ParsingException[Expecting '"' for string start. Found } at position: 617]
the code:
class A{
Map<String,B> b;
}

data:
 {"b":{}}

so i think there has an error in com.dslplatform.json.JsonReader#readMap, 

if (getNextToken() == ']') return new LinkedHashMap<K, V>(0)  should be  if (getNextToken() == '}') return new LinkedHashMap<K, V>(0)

**Comment by zapov** [comment]
Indeed.
Can you write a test and a fix for it?

**Comment by zapov** [comment]
Tnx for the bug report. Fixed in latest commit: https://github.com/ngs-doo/dsl-json/commit/efeb098fab57258e57f1d0d821c4b73dfa942267

**Comment by zapov** [comment]
Fix released in v1.9.4
