### ISSUE TITLE
Deal with Umlaut (ä, ö, ü, or ß) in input

### ISSUE THREAD

**Issue by james-woods** [ngs-doo/dsl-json#14]
The following JSON breaks the parser with 
`SEVERE: IOException parsing entry: Unexpected end of JSON input`

```
{
	"@timestamp": "2016-09-05T12:44:46.000Z",
	"url": {
		"analyzed": "/-/-/call-1111",
		"path": "/-/-/call-1111",
		"query": {
			"was": "sägewerk gmbh"
		}
	},
	"event": "view",
	"origin": "detail",
	"session": ["-9035111172716044880", "6141211111163737100", "-6891111112685400843", "-275111111849250600"],
	"@version": "1"
}
```

(The `was` field contains user input which includes HTML-valid Umlaute as ä,ü,ö, or ß.)

**Comment by zapov** [comment]
That sounds horribly wrong (like something which ought to work).

Can you provide a test case? This works:

    @Test
    public void testUmlat() throws IOException {
        String input = "\"sägewerk gmbh\"";
        DslJson<Object> dslJson = new DslJson<Object>();
        byte[] bytes = input.getBytes("UTF-8");
        String result = dslJson.deserialize(String.class, bytes, bytes.length);
        Assert.assertEquals("sägewerk gmbh", result);
    }

Note the getBytes("UTF-8") if you are converting from string.

**Comment by james-woods** [comment]
Thanks for the UTF-8 hint! The other mistake I made was using the length of the string instead of the length of the (converted) buffer - breaks with umlauts of course.
