### ISSUE TITLE
NaN support

### ISSUE THREAD

**Issue by mmelsen** [ngs-doo/dsl-json#142]
Hi,

I'm looking at dslJson to replace jackson. In Jackson I can enable a property to allow NaN values to be deserialized to Double.NaN for example. If I provide a json like:
`{ "timestamp": 39933939, "value": NaN}` then I get a parseexception from dslJson. 

I looked at https://github.com/ngs-doo/dsl-json/blob/3e720f52f3dd49c36c82b7227584b88c0188cb16/library/src/test/java/com/dslplatform/json/generated/types/Double/NullableArrayOfNullableDoublesDefaultValueTurtle.java#L44 and noticed that this can deal with NaN values. However I don't find JsonSerialization in my maven dependency. Does dslJson also provide support for NaNs?

**Comment by zapov** [comment]
It does, but it requires that NaN is quoted, because otherwise it's not really a valid JSON.
If you require such unquoted NaN, you'll have to specify custom Double/property parser and deal with it there (eg, if value starts with N parse it as NaN otherwise just redirect to default parser.

**Comment by zapov** [comment]
There is partial example on how to deal with unquoted NaN: https://github.com/ngs-doo/dsl-json/blob/master/library/src/test/java/com/dslplatform/json/NumberConverterTest.java#L1295
ps. it does not take care of all use cases
