### ISSUE TITLE
Interface Serialization on Android

### ISSUE THREAD

**Issue by MoBran** [ngs-doo/dsl-json#146]
Hey,

I am having troubles serializing an interface on Android using DSL. When i run the demo code ([Polymorphism-Demo](https://github.com/ngs-doo/dsl-json/tree/master/examples/Polymorphism/src/main/java/com/dslplatform/polymorphism)) on a device with Android version 9 everything works as expected. But when I run the example code on a device with an older Android version, e.g. 5.1.1. I get the following error thrown:

`java.lang.NoSuchMethodError: No interface method getTypeName()Ljava/lang/String; in class Ljava/lang/reflect/Type; or its super classes (declaration of 'java.lang.reflect.Type' appears in /system/framework/core-libart.jar)
        at com.dslplatform.json.runtime.FormatDescription.<init>(FormatDescription.java:56)
        at com.nifdex.npay.mobile.test.json._AbstractClass_DslJsonConverter.configure(_AbstractClass_DslJsonConverter.java:7)
        at com.dslplatform.json.ExternalConverterAnalyzer.tryFindConverter(ExternalConverterAnalyzer.java:23)
        at com.dslplatform.json.DslJson.lookupFromFactories(DslJson.java:1093)
        at com.dslplatform.json.DslJson.tryFindWriter(DslJson.java:1035)`

When looking at the FormatDescription constructor, I see that the error is thrown because it tries to get the type name through the function manifest.getTypeName(), which does not seem to exist on older Android versions. Since I already provide the typeName via the constructor, there is no need to get it through reflection again? Is there a way to make it work on older Android versions?

**Comment by zapov** [comment]
Sure, it's something which can be improved.
We can have some utility method to call into which would be try to print name in more robust way.

As for the other argument, it can be changed (it does not need to match class name) so it can't really be used for that purpose.

If you want to provide PR for that, go ahead.

**Comment by zapov** [comment]
I've added such guards in place.
Please let me know if its working now and if there are any other issues to resolve before next version.

**Comment by zapov** [comment]
Improvements added in v1.9.4
