### ISSUE TITLE
Compilation error when Abstract class and Subclass are in different packages

### ISSUE THREAD

**Issue by Danielyt** [ngs-doo/dsl-json#149]
The generated code does not compile if the Abstract class and its subclasses are in different packages. A generated constructor has package private visibility instead of public. This is the error that I get:

Compilation failure
[ERROR] /C:/dev/sandbox/dsl-json/examples/MavenJava8/target/generated-sources/annotations/com/dslplatform/maven/parent/_BaseEntity_DslJsonConverter.java:[11,131] ObjectFormatConverter(com.dslplatform.json.DslJson) is not public in com.dslplatform.maven.child._ChildEntity_DslJson
Converter.ObjectFormatConverter; cannot be accessed from outside package

**Comment by zapov** [comment]
Tnx. Can you make a PR with a test which fails? I can look into fixing it then

**Comment by Danielyt** [comment]
I've created a pull request exemplifying the problem:
[https://github.com/ngs-doo/dsl-json/pull/152](pull request)

**Comment by zapov** [comment]
Tnx. Will look into it this week

**Comment by zapov** [comment]
Should be resolved with latest commit. I'll look into making a new version before years end

**Comment by zapov** [comment]
Fix released in v1.9.4
