### ISSUE TITLE
External annotation support

### ISSUE THREAD

**Issue by JakeAngell** [ngs-doo/dsl-json#15]
In the readme it says that this library supports external annotations like Jackson's @JsonProperty. Can't find any example of an annotation being used to change the name used for deserialization/serialization declared outside of the model class itself.

In Jackson I'd just create a new mixin class and register it with my object mapper. Is their similar support for dsl-json?

Thanks

**Comment by zapov** [comment]
Not currently.
JsonProperty annotation is only inspected on target classes.
It's something which I guess could be "easily" improved in the annotation processor.

You can do it by writing DSL and running compiler on it, but I guess that's not really dev-friendly solution.

Can you provide a more concrete example, maybe there is something else which can be done for this use case?

**Comment by JakeAngell** [comment]
Basically I have a model class and I'm deserializing multiple different JSON structures into this singular model. Adding a @JsonProperty annotation directly to this POJO would not be correct for every JSON structure.  

Not the best solution but would using @JsonAttribute(alternativeNames=<possible-names>) and listing all of the possible field names for each JSON structure work? 

Let me know if this makes sense or I can go into more depth and add some concrete examples.

**Comment by zapov** [comment]
Yes, that seems like a good use case for alternativeNames.

**Comment by JakeAngell** [comment]
Using this approach does not seem to work. I have a top level model class that contains another complex type. 

```
import com.dslplatform.json.CompiledJson;
import java.util.List;
@CompiledJson
public class Model {
    private List<SubModel> subModels

    public Model() {}

    public Model(List<SubModel> subModels) {
        this.subModels = subModels;
    }
}
```

```
import com.dslplatform.json.JsonAttribute;
public class SubModel {
    @JsonAttribute(alternativeNames= {"somevar"})
    private float someVar = 0;
    @JsonAttribute(alternativeNames= {"someothervar"})
    private String someOtherVar = "value";
}
```

A call to dslJson.deserialize(Model.class, jsonString.getBytes(), jsonString.length()) where dslJson is initialized as DslJson<Object> does not deserialize correctly. 

However, changing the json string manually to be camelCased to match the model results in correct deserialization.

I use the following Maven dependencies. 
```
        <dependency>
            <groupId>com.dslplatform</groupId>
            <artifactId>dsl-json</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.dslplatform</groupId>
            <artifactId>dsl-json-processor</artifactId>
            <version>1.4</version>
            <scope>provided</scope>
        </dependency>
```

**Comment by zapov** [comment]
I don't think those attributes are picked up on private fields. Can you try putting them on getters? Or make fields public

**Comment by JakeAngell** [comment]
I tried making one field public and it had no effect, I'll try putting the attribute on the getters. 

Thanks for the quick replies by the way.

**Comment by JakeAngell** [comment]
Placing the attributes on a getter for the private fields did the trick. Thanks.

Unsure why it did not work when I made one of the variables public like in your examples though.

**Comment by zapov** [comment]
It should work. But maybe your field in Model was not public, so annotation was not implicitly propagated.

**Comment by JakeAngell** [comment]
Ah yeah, that'll be it no doubt, the field in Model was private. Great, thanks.

**Comment by prasannajoshi2121** [comment]
Hi @zapov ,

but this is not proper solution right ?? as we cannot add this annotation if we are using Lombok generated Getters .... any solution for that ??
