### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by imrafaelmerino** [ngs-doo/dsl-json#150]
Hi,

I'm considering to use this library to parse strings into maps. The thing is that doing some performing and comparing with Jackson, the latter turns out to be faster. I expected it to be the other way around. I might be missing something or it is what it is in this scenario, where the Json schema is not specified and the string is not deserialized into a POJO. 
Of course, I take the results I got with a pinch of salt, and that's why I'm asking for some feedback, to get a better knowledge about the advantages of DSL-JSON over Jackson.

```
private static DslJson<Object> dslJson = new DslJson<>();
private static ObjectMapper mapper = new ObjectMapper();
private static bytes[] jsonObject = createJsObj();   

@Benchmark
public JsonNode jackson() throws IOException
{
     return mapper.readTree(jsonObject);
}

@Benchmark
public Object dsljson() throws IOException
{
     return dsljson.deserialize(Map.class,jsonObject,jsonObject.length )
}
```

Benchmark   Mode  Cnt       Score          Error             Units
jackson         thrpt    25  **319147** ± 9683.657        ops/s
dslJson         thrpt    25  **275684** ± 3903.296       ops/s

**Comment by plokhotnyuk** [comment]
@imrafaelmerino Hi, Rafael!

It can depend heavily on payload and environment. [Here](https://plokhotnyuk.github.io/jsoniter-scala/) are results on benchmarks for payload of different types on different JVMs and in most cases DSL-JSON outperform Jackson.

Even [a version of CPU microcode](https://github.com/oracle/graal/issues/1829) is matter.

Also, you can use different profilers like: [async-profiler](https://github.com/jvm-profiling-tools/async-profiler) to get flame graph of CPU usage or JMH's [perfasm](http://psy-lob-saw.blogspot.com/2015/07/jmh-perfasm.html) with [perfnorm](https://shipilev.net/jvm/anatomy-quarks/2-transparent-huge-pages/) to see what is happening on a level of CPU instructions.

**Comment by imrafaelmerino** [comment]
Thank you very much for your thorough response!  I'm running my tests in

2,4 GHz Intel Core i5
16 GB 2133 MHz LPDDR3
macOS Mojave 10.14.6

I've tried with payloads of different sizes (from 50 to 1000). In all cases Jackson outperforms dsl-json. I know performance is a tricky thing, that's why I haven't reached any conclusion yet and I'm asking...  

The results you got reveal how dsl-json is the fastest in most cases, but what about the case I'm talking about, I mean, **no codecs**,  just deserializing a string into a map **without specifying the schema of the Json**

Regards

**Comment by zapov** [comment]
DSL-JSON was heavily optimized to work with schemas. While it can do non-schema deserialization, there is only so much you can do there... and since this was not as interesting to me, its not better by leaps and bounds from Jackson in that regard.

Author of Jackson made a relevant benchmark a while ago: https://github.com/cowtowncoder/java-json-performance-benchmarks/wiki where you can see that when it comes to Maps (no schema) they perform about the same.

So yes, there are certainly some optimizations which could be done in that regard, as the ones you suggested, but it was never my focus.

**Comment by imrafaelmerino** [comment]
Ok, I understand. It makes sense to me. I'd like to develop a mixed approach, I mean, deserialize into a map but defining its schema at the same time.  For example, given the schema of a map

"a" -> object
"a.b" -> int
"a.c" -> string
"a.d" -> arr of ints
...

to use that information to deserialize along the process, instead of working out what deserializer to use every parsed token. I think it would improve performance for our case. Then entry point could be the Json Shema Specification for example. Well, I'll stick to DSL-JSON and keep working on this.

Thank you for your time and for your quick answer...
