### ISSUE TITLE
PrettifyOutputStream

### ISSUE THREAD

**Issue by imrafaelmerino** [ngs-doo/dsl-json#154]
According to the README document, this is the way of creating a formatted Json:
```
dslJson.serialize(instance, new PrettifyOutputStream(outputStream));
```

but I can't find the class **PrettifyOutputStream**

Am I missing something?

I'm using the version **1.9.3**

Regards

**Comment by plokhotnyuk** [comment]
Hi, Rafael!

Have you added an additional dependency with the `dsl-json-java8` artifactId?

**Comment by imrafaelmerino** [comment]
that made the trick! thanks
