### ISSUE TITLE
Skip item, when field null, but field it is non-nullable

### ISSUE THREAD

**Issue by svzj95** [ngs-doo/dsl-json#159]
Hi guys, how to set field value, which allows to skip item, if it has value in field null, but it can not be null.

**Comment by zapov** [comment]
Please provide more context around what you are doing, whats not working, what you are expecting to work differently as I can only guess about your problem.
If nothing else works, you can always have custom converter per field: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L40

**Comment by svzj95** [comment]
> Please provide more context around what you are doing, whats not working, what you are expecting to work differently as I can only guess about your problem.
> If nothing else works, you can always have custom converter per field: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L40

Let's consider case 1. there is pojo class with field of different class:
`
@CompiledJson(onUnknown = CompiledJson.Behavior.IGNORE)
public statuc class JsonData {
    List<Station> stations;

    @CompiledJson(onUnknown = CompiledJson.Behavior.IGNORE, formats = CompiledJson.Format.OBJECT)
    static class Station {
        @JsonAttribute(nullable = false)
        public Long id;
        public Long capacity_cars;
    }
}
`
also i provide a few jsons
thre is json1.
`
{
 'stations" : [{
   "id" : null,
   "capacity_cars" : 232
},
{
   "id" : 23,
   "capacity_cars" : 232
}
]
}
`
In case of json1 i will get 
Exception in thread "main" com.dslplatform.json.ParsingException: Property 'station' is not allowed to be null at position

Therefore it is question: "How can i do, that i have only 1 valid object of Station in the end of parsing?"

**Comment by zapov** [comment]
If you want that List stations contains only a single element at the end of parsing, you'll have to attach the converter I linked above to that list property. So you deserialize elements in the converter and decide there which one you want to return.
