### ISSUE TITLE
How to deserialize single value into a specified field in an object

### ISSUE THREAD

**Issue by nwb-rony** [ngs-doo/dsl-json#162]
Hi. Amazing work with this lib, thanks :)

I have a strange scenario in which I receive a json and a string and I need to deserialize both of them into one object.
What would be the most performant way to do that?

Example:
**Input (protobuf)**
json=" {"a": "avalue", "b": "bvalue"} "
string= "SOME STRING"

**Target Object**
```
public class MyObject {
    public String a;
    public String b;
    public String c;
}
```

I want to push the string into the appropriate `c` field, but it should work with every target class that have a field pointing to a json `c`.

Is there any easy way to first deserialize the json into MyObject and then deserialize the string into a `c` field in MyObject?

Thanks.

**Comment by zapov** [comment]
I'm not really fully following what you are trying to do, as it's not clear what JSON and a string means. Is this from the same input? How do you differentiate that scenario from other with ordinary JSON.

Anyway,... there is a bind API so you can actually use existing instances for processing input JSON. That might be what you want, but it's hard to tell.
Here is an example of manual definition of such usage: https://github.com/ngs-doo/dsl-json/blob/1ab72fa38dd02e2ae4dab4fa041d4e9c3998a079/library/src/test/java/com/dslplatform/json/ReaderTest.java#L236 but you can register your own with same interfaces to push into c "fields"

**Comment by nwb-rony** [comment]
Thanks.
Sorry if I wasn't clear, I will try to explain better:
I receive an input that is represented like this:
```
public class MyInput {
    public String jsonString;     <--- value looks like "{"a": "value", "b": "value"}"
    public String cFieldValue;   <--- value looks like "Some string"
}
```
And I have a target class:
```
public class MyObject {
    public String a;
    public String b;
    @JsonAttribute(name = "c")      <--- this can be a jackson attribute as well
    public String anUnknownFieldName;
}
```

What I want to do is to deserialize `jsonString` into MyObject (this will fill `a` and `b`), then "deserialize" (or more precisely - set) `cFieldValue` into `anUnknownFieldName`.

From your answer, I understand that the only solution is to register my own binder and implement him in a way that looks for `c` fields in the object? Do you have any example of how this should be done?

Thanks

**Comment by zapov** [comment]
I'm still missing some context on what you are doing, but there is a test now which shows such usage: https://github.com/ngs-doo/dsl-json/commit/4412e0a4c2a869b0962bd3889520a304aade834d

Hopefully that gets you on track.
