### ISSUE TITLE
Converter fails to find serializer

### ISSUE THREAD

**Issue by mecoFarid** [ngs-doo/dsl-json#164]
I've tried to test the serialization policy with a given code sample in the Android (Gradle) project. 
https://github.com/ngs-doo/dsl-json/blob/7f06827328be937b2f1798683078092f847f78ff/tests-java8/src/test/java/com/dslplatform/json/ObjectFormatPolicyTest.java

But I got the following error:

> com.dslplatform.json.ConfigurationException: Unable to serialize provided object. Failed to find serializer for: class com.xxxx.xxxxx.DslJsonSerializationTest$User4

**Comment by zapov** [comment]
Hi

If you can help setting up Kotlin test project that would be a great first step in resolving Kotlin issues.
I just pushed a branch here: https://github.com/ngs-doo/dsl-json/tree/kotlin-tests but it fails to compile ;(

**Comment by mecoFarid** [comment]
Hi, sure I'd be happy to contribute

**Comment by zapov** [comment]
There are now Kotlin tests and improved Kotlin support in v1.9.6.
v1.9.6 released
