### ISSUE TITLE
wrong stacktrace when EOF

### ISSUE THREAD

**Issue by bachden** [ngs-doo/dsl-json#165]
in class `com.dslplatform.json.JsonReader<TContext>` has a private final EOF exception (at line 306). It made wrong stacktraces when 2 threads use the same DslJson object both throw EOF exception.

**Comment by zapov** [comment]
Ah, I see the override to fillInStackTrace for that marker exception was missing.

Fixed it in latest commit: https://github.com/ngs-doo/dsl-json/commit/a40d55d638f7354027d9ed4258cb51c7a0e01cc3

**Comment by khoatruongtaka** [comment]
In my case, it's alway throw the last EOL exception (stick with it). Thank for your fix!
![image](https://user-images.githubusercontent.com/23315517/74897640-4be4b380-53ca-11ea-959b-a5dc8af297cf.png)

**Comment by dekatruong** [comment]
In my case, it's alway throw the last EOL exception (stick with it). Thank for your fix!
![image](https://user-images.githubusercontent.com/12489468/74898000-2d32ec80-53cb-11ea-84fe-a203012c774b.png)

**Comment by bachden** [comment]
> Ah, I see the override to fillInStackTrace for that marker exception was missing.
> 
> Fixed it in latest commit: [a40d55d](https://github.com/ngs-doo/dsl-json/commit/a40d55d638f7354027d9ed4258cb51c7a0e01cc3)

I saw it. Thanks!

**Comment by zapov** [comment]
v1.9.6 released

**Comment by dekatruong** [comment]
Very Good, Thank guys!
