### ISSUE TITLE
Unable to find annotation 

### ISSUE THREAD

**Issue by rwilliams-r7** [ngs-doo/dsl-json#167]
I am trying to use on my object

```
 @JsonAttribute(converter = ConvertValue.class) 
String value;
```
with Convertor  

```
   public static abstract class ConvertValue {
        public static final JsonReader.ReadObject<String> JSON_READER = new JsonReader.ReadObject<String>() {
            public String read(JsonReader reader) throws IOException {
                 return ";"
            }
        };
        public static final JsonWriter.WriteObject<String> JSON_WRITER = JsonWriter::serializeObject;
    }
```

But my convertor never get called I do not get an error and the only thing I can see is that I get this warning at compile time

`Warning:java: No processor claimed any of these annotations: com.dslplatform.json.JsonAttribute dsl-json`

I am using Java 11 and the dependency 

```
<dependency>
            <groupId>com.dslplatform</groupId>
            <artifactId>dsl-json-java8</artifactId>
            <version>1.9.5</version>
        </dependency>
```

Any idea why this would be happening?

**Comment by rwilliams-r7** [comment]
So looks like the property on my value within my object needs to be public is this correct?

**Comment by zapov** [comment]
Yes, it needs to be public. Not sure this was made a warning in the meantime, but it definitely should be a warning

**Comment by zapov** [comment]
This should report a warning which seems sufficiently good.
