### ISSUE TITLE
Support sort_keys=true for serialization

### ISSUE THREAD

**Issue by ericsun2** [ngs-doo/dsl-json#168]
Is it possible to add support to recursively sort JSON by keys, similar to [sort_keys=true](https://docs.python.org/3/library/json.html) in Python?

Similarly, https://www.javadoc.io/static/com.alibaba/fastjson/1.2.68/com/alibaba/fastjson/serializer/SerializerFeature.html#SortField 
and 
https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-databind/latest/com/fasterxml/jackson/databind/SerializationFeature.html#ORDER_MAP_ENTRIES_BY_KEYS can do the trick.

**Comment by zapov** [comment]
It shouldn't be too hard to add it similarly to how minification is done: https://github.com/ngs-doo/dsl-json/blob/2fd1e9a6fd745baa719857363d4d82befa995661/library/src/main/java/com/dslplatform/json/processor/Analysis.java#L568

You could reorder attribute map alphabetically. I guess if there is custom order defined it should trump this sorting definition.

**Comment by plokhotnyuk** [comment]
@ericsun2 What to do with maps or custom codecs with can serialize something into JSON objects?

**Comment by ericsun2** [comment]
If dsl-json can sort map/dict or custom object based on the byte[] of the key, that will be sufficient. The goal is to have an option to always generate exactly the same JSON string regardless of the order in the source.

**Comment by plokhotnyuk** [comment]
But sorting will change the order if the source has different order.

Could you please give more context for your case to select the best solution?

**Comment by ericsun2** [comment]
`sorting` is an option, it is not the default behavior.

The most common use case is to compare 2 JSON(s) and determine if they are the same. So even if the source keys order inside the Map (at any nested levels) can be different, after sorting, the JSON string can be truly comparable.

This is a popular use case when JSON is used as the configuration or data payload, the comparison/diff **can not** be done between raw strings, the sorting is required.

**Comment by plokhotnyuk** [comment]
So it looks more like the XY problem. Now you are trying to resolve some comparison of output challenge by altering the library. Please consider using of proper tool for JSON comparison instead.

**Comment by zapov** [comment]
As naming strategy should be working now I'll close this
