### ISSUE TITLE
Support for non-serialization of null fields

### ISSUE THREAD

**Issue by JakeAngell** [ngs-doo/dsl-json#17]
Would it be possible to add a setting to avoid the serialization of a field if it is null? Or to conditionally apply the @ignore annotation. 

Currently I am serializing a POJO that has nullable fields with a requirement to only serialize non-null values. In Jackson it could be achieved with a @JsonInclude(JsonInclude.Include.NON_NULL) annotation.

**Comment by zapov** [comment]
There is a settings in DslJson to omit serializing "default" values: https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/DslJson.java#L122

**Comment by zapov** [comment]
But it seems this is ignored during registration in generated code. I'll look into what can be done about it...

**Comment by JakeAngell** [comment]
Okay great, thanks a lot for another quick reply and looking into this

**Comment by zapov** [comment]
New version is available and has a fix for this.
Let me know how it goes.

**Comment by JakeAngell** [comment]
Moving to dsl-json 1.3.1 and dsl-json-processor 1.4.1 I can't seem to resolve any imports. IntelliSense only picks up import com.dslplatform.json.CompiledJsonProcessor.

**Comment by zapov** [comment]
Strange.
IDEA? Clear cache?

**Comment by JakeAngell** [comment]
No change unfortunately.

**Comment by JakeAngell** [comment]
Pom looks like this

`        <dependency>
            <groupId>com.dslplatform</groupId>
            <artifactId>dsl-json</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.dslplatform</groupId>
            <artifactId>dsl-json-processor</artifactId>
            <version>1.4.1</version>
        </dependency>`

**Comment by zapov** [comment]
It works on several of my machines... so there is something broken at your end.
I would try...
adding <provided> to processor dependency (this should be default anyway)
Trying out 1.3.0
Trying with 1.4 just to see if it works as previously
Running Maven from cmd and looking if it works there

**Comment by JakeAngell** [comment]
1.3.0 and 1.4/1.4.1 works fine, only get the issue with 1.3.1. At least I know it's an issue my side now so I'll debug. Will let you know how omitting defaults goes when I get this working.

**Comment by JakeAngell** [comment]
Turned computer back on after weekend and works perfectly :). Weird.

Omitdefaults setting works perfectly now, in case anyone else stumbles upon this make sure to include a call to ServiceLoader in your DslJson constructor. I created my instance like this: 

dslJson = new DslJson<>(null, false, null, true, null, ServiceLoader.load(Configuration.class));
