### ISSUE TITLE
Skip properties by default?

### ISSUE THREAD

**Issue by Jonatino** [ngs-doo/dsl-json#171]
Is it possible to configure this to skip all properties by default unless specifically included?

**Comment by zapov** [comment]
Not currently. We could support it via new enum value in serialization policy: https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/CompiledJson.java#L67

Something like EXPLICIT

**Comment by zapov** [comment]
Added in last commit: https://github.com/ngs-doo/dsl-json/commit/c46aa403b52c913d6d5a19551ab1d70b7f889ba4

**Comment by zapov** [comment]
v1.9.6 released
