### ISSUE TITLE
kotlin code using inheritance with an abstract class doesn't serialize abstract class field

### ISSUE THREAD

**Issue by abnud1** [ngs-doo/dsl-json#173]
We have a kotlin backend project, We're using dsl-json as the JSON serialization library and we have code similar to this:
```kotlin
@CompiledJson
abstract class A(val t: String)

@CompiledJson
class B(val r: String) : A("hello")
```

The problem that happens is that when serializing B object t property in A class is not serialized, By looking at the generated code We see no trace for the t property.

We tried multiple configuration options for `@CompiledJson` annotation like `minified = false`, changing include policy, We even used `JsonAttribute` annotation like this:
```kotlin
@CompiledJson
abstract class A(
    @JsonAttribute(mandatory = true)
    val t: String
)
```
But to no avail, here is how We configure the DslJson instance:
```kotlin
val dsljson = DslJson<Any>(
    Settings.basicSetup<Any>()
        .skipDefaultValues(false)
)
```
We tried multiple things at this code, again nothing works.

Here is full code with example serializing code:
```kotlin
@CompiledJson
abstract class A(val t: String)

@CompiledJson
class B(val r: String) : A("hello")
fun main(){
    val dsljson = DslJson<Any>(
        Settings.basicSetup<Any>()
            .skipDefaultValues(false)
            .includeServiceLoader()
    )
    FileOutputStream("t.json").use {
        dsljson.serialize(B("toto"), it)
    }       
}
```

we're using the latest version of dsl-json, kotlin is at 1.4, we're using kapt annotation processor
and gradle 6.6.

OS is Windows 10 x64
Java version is 11

**Comment by zapov** [comment]
Pattern like this seems to work

```
@CompiledJson
class B(val r: String, t: String) : A(t) {
    constructor(r: String) : this(r, "hello") {}
}
```

It would be of great help if someone invested some time and setup a Maven project for testing Kotlin: https://github.com/ngs-doo/dsl-json/issues/158
It's kind of hard to support non-trivial use cases without it

**Comment by abnud1** [comment]
@zapov I created a maven project that will illustrate the issue

find it [here](https://github.com/abnud1/dsljson-maven-demo)

**Comment by zapov** [comment]
Hi @abnud1 
I tried to create such testing project in February, but gave up...

It would be great if someone can make: https://github.com/ngs-doo/dsl-json/tree/kotlin-tests runnable

I can come closer by doing some hacks, eg putting Kotlin files in main instead of tests, but still it fails due to some dependency problem which I don't really have time to look into.

If you can make that branch compiling and tests running that would be a great start for improved Kotlin support

**Comment by abnud1** [comment]
Well `mvn test` now builds but the test doesn't run.

And the process is unfortunately very confusing, you have to execute test on parent project not submodule, if you don't want to test all the modules you use `-pl subprojectgroupid:subprojectartifactid` so command in our case is `mvn -pl com.dslplatform:dsl-json-integration-tests-kotlin test -am`, you run the command in root project directory, the `-am` is required otherwise it won't build.

I'll have to see later why the test isn't run even though maven show no errors at all, even with simple `mvn test` on root project I don't think the kotlin test is run(although I'm not sure really, very big output you know)

**Comment by zapov** [comment]
I'm fine with writing Java code for tests which uses Kotlin classes. If you can get that to work via mvn test that should be more than good enough

**Comment by zapov** [comment]
This should now work as "expected". Please look over and report back :)

Also finally managed to setup Kotlin tests, so it should be easier to resolve such cases in the future :tada:

**Comment by zapov** [comment]
v1.9.6 released
