### ISSUE TITLE
Model classes from external library/jar support

### ISSUE THREAD

**Issue by prasannajoshi2121** [ngs-doo/dsl-json#174]
Hi ,
I am trying explore this library and understand feature , I am trying to provide @CompiledJosn on model classes from external project and adding that model-jar dependency in my project where i am trying serialize and deserialize those model classes.

Like , 
Project A  - having Jar dependency ( Project-b)

main class {
  DslJson<Object> dslJson = new DslJson<>(Settings.basicSetup());
dslJson.deserialize(Model.class, ary, ary.length);

and in other use case

ByteArrayOutputStream out = new ByteArrayOutputStream();
    try {
      dslJson.serialize(modelresponse, out);
}

Project B 
@CompiledJson 
Model {
@JsonProperty
String xyz
getter/setter
}

Also one thing I noticed that , in my library Model_DslJsonConverter classes getting created under targert/class and target/generated sources but jar is not having those ... 

library version =:
      <dependency>
      <groupId>com.dslplatform</groupId>
      <artifactId>dsl-json-java8</artifactId>
      <version>1.9.6</version>
    </dependency>

**Comment by zapov** [comment]
Hi,

I'm not sure I understand the problem/question here.
What do you mean by "but jar is not having those"? The jar created for your project? Or when you use model-jar dependency it does not pick up definitions in the your new jar? If thats the problem, you can actually provide settings to maven to create extra file which you can load during DslJson initialization, although I would expect to work out-of-the-box if you have your jar on classpath.

**Comment by prasannajoshi2121** [comment]
Hi ,
 let me try to explain it again ,

Project - A :  maven based project which contains on only model classes annotated with @compiledJson annotation.
i am packaging as JAR and pushing it to nexus repo. I can see inside my jar i am having all Model_DslJsonConverter classes under same package where my model classes are present.

Exmaple -  Project-A-SNAPSHOT.Jar  , inside this jar i am having

com -
         test- 
               SampleModel.class ( the class which is annotated with @CompiledJson)
               _SampleModel_Model_DslJsonConverter.claas (generated class)

Note- In your documentation its mentioned that 

_"Processor will register optimized converters into META-INF/services. This will be loaded during DslJson initialization with ServiceLoader."_

This project is not generating META-INF/service folder during packaging.



Now i am importing this Project-A-SNAPSHOT.Jar as dependency in my another project. In this project i am actually trying to convert JSON to this SampleModel.class which is working ONLY when i am using reflection option 

DslJson<Object> dslJson =new DslJson<>(Settings.withRuntime())

**But its not working when I am using** 

DslJson<Object> dslJson =new DslJson<>(Settings.basicSetup())

or 

DslJson<Object> dslJson = new DslJson<>(Settings.basicSetup().includeServiceLoader());

**Comment by zapov** [comment]
As far as META-INF goes, we've disabled this by default few years ago in favor of more simplistic lookup based discovery.
You can still create them by specifying maven configuration: https://github.com/ngs-doo/dsl-json/blob/1ac0a0a9a142fe5874b30c42c8fb798aeb505c16/java8/src/main/java/com/dslplatform/json/processor/CompiledJsonAnnotationProcessor.java#L169

I wonder if this is some new Java module/visibility issue. If you can create a reproducible project that would be great. As temporary alternative, I suggest you try to set configuration parameter in model jar and explicitly include that configuration during initialization. I remember I didn't want to fully remove this configuration to support full compile time dependency discovery for Java AOT compilation.

**Comment by prasannajoshi2121** [comment]
working now , closing this.
