### ISSUE TITLE
How do you serialize Map with key other than String ?

### ISSUE THREAD

**Issue by unoexperto** [ngs-doo/dsl-json#189]
Perhaps it was answered before but I couldn't find it neither in tests nor in documentation.

How would you serialize `Map` with key other than `String` ? One of my POJOs has field of type `Map<Long, Something>`. Is there idiomatic way to do it with dsl-json with minimum boilerplate?

I'm using dsl-json in kotlin.

**Comment by zapov** [comment]
Doesn't this work out of the box?
There is relevant example with enums here: https://github.com/ngs-doo/dsl-json/blob/master/tests-java8/src/test/java/com/dslplatform/json/EnumTest.java#L62

I would expect if you use that exact signature it will work.
Although it will quote keys (which are longs) - to make JSON valid.

**Comment by plokhotnyuk** [comment]
@unoexperto I'm using DSL-JSON in Scala. Please [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/ed21d7b6934077166d9ed517e73a35c41d34c128/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/DslPlatformJson.scala#L57) for creation of `Map[Int, Boolean]` encoder/decoder and [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/ed21d7b6934077166d9ed517e73a35c41d34c128/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/DslPlatformJson.scala#L74-L85) for methods for parsing and serialization from/to byte arrays.

**Comment by unoexperto** [comment]
Thank you for prompt response, guys. It didn't work out of the box but using `com.dslplatform.json.runtime.Settings.basicSetup()` helped. Could you please explain the reason it helped ?

**Comment by zapov** [comment]
You should check if annotation processor is running.
Search for _DslJsonConverter in target folder for your class. Also check if it has `@CompiledJson` annotation on it

**Comment by unoexperto** [comment]
> You should check if annotation processor is running.

It was. Before I had Map issue I had compilation error caused by field that was named `isArray: Boolean`. I think preprocessor couldn't create properly named setter/getter in produced .java file. I had to rename it to `array: Boolean`.

**Comment by zapov** [comment]
Using `basicSetup()` most likely caused runtime analysis to kick in. There is some setup problem if it doesn't work without it.
But without more info its hard to tell.

**Comment by unoexperto** [comment]
I see. If there is performance penalty for using runtime analysis in my case and it should have worked without it I'll create isolated test-case and will it post it here later.

**Comment by unoexperto** [comment]
@zapov I apologize for using this issue as customer support but I have one more question. So I tried to remove runtime analysis to test if `Map<Long, Something>` conversion would work but it failed for following case/data class

```
@CompiledJson
data class PsqlTable(val oid: Long,
                              val name: String,
                              val columns: Map<Int, PsqlColumn>,
                              val indices: List<PsqlIndex>,
                              val byteSize: Long?)

@CompiledJson
data class PsqlIndex(val columns: List<Int>, val type: IndexType)

@CompiledJson
data class PsqlType(...only primitive types...)
```

with exception

```
Exception in thread "main" com.dslplatform.json.ConfigurationException: Unable to find writer for java.util.List<com.zzz.source.postgres.PsqlIndex>. Enable runtime conversion by initializing DslJson with new DslJson<>(Settings.basicSetup())
	at com.zzz.source.postgres._PsqlTable_DslJsonConverter$ObjectFormatConverter.writer_indices(_PsqlTable_DslJsonConverter.java:34)
	at com.zzz.source.postgres._PsqlTable_DslJsonConverter$ObjectFormatConverter.writeContentFull(_PsqlTable_DslJsonConverter.java:99)
	at com.zzz.source.postgres._PsqlTable_DslJsonConverter$ObjectFormatConverter.write(_PsqlTable_DslJsonConverter.java:83)
	at com.zzz.source.postgres._PsqlTable_DslJsonConverter$ObjectFormatConverter.write(_PsqlTable_DslJsonConverter.java:14)
```

Do I have to enable runtime analysis in order to serialize generic containers ?

**Comment by zapov** [comment]
You shouldn't have to.
But Kotlin uses some strange types which might not be supported in such cases out of the box.

We now finally have Kotlin tests running via: https://github.com/ngs-doo/dsl-json/tree/master/tests-kotlin/src/main/kotlin/com/dslplatform/json

so I'll look into it when I find some time.
Is it working with runtime analysis?

**Comment by unoexperto** [comment]
Guys, I'll close this issue because it seems like it was compilation problem or IDEA's problem. I couldn't reproduce the exception in test project and then I couldn't reproduce it in original project after deleting .idea, build and out folders. Sorry for false alams.
