### ISSUE TITLE
1.9.7 when its going to be available in Maven central ?

### ISSUE THREAD

**Issue by prasannajoshi2121** [ngs-doo/dsl-json#190]
:) please let me know when it will be available in Maven ?

**Comment by zapov** [comment]
I can look into releasing it early next month.
Is there some urgency to it?

**Comment by prasannajoshi2121** [comment]
@zapov actually I if you could it would really help :) , as I wanted to test few things with that .

**Comment by zapov** [comment]
Can you test without a new maven release? That would certainly help me :)

**Comment by prasannajoshi2121** [comment]
sure , up to you when you want to release :). Just keeping issue open so that you can update me here once its released to maven.

**Comment by zapov** [comment]
v1.9.7 released
