### ISSUE TITLE
Discriminator is not written to resulting json

### ISSUE THREAD

**Issue by unoexperto** [ngs-doo/dsl-json#192]
For some reason `@type` field is not written to json in the following example:

```
@CompiledJson(discriminator = "@type")
interface Base2

@CompiledJson(name = "one")
data class One(val value: String): Base2

@CompiledJson(name = "two")
data class Two(val value: Long): Base2

fun main(args: Array<String>) {
    val mapper = DslJson<Any>()

    val testList: List<Base2> = listOf(One("message"), Two(1917))
    val jsonList = mapper.encodeAsString(testList)
    val decodedList = mapper.decodeString<List<Base2>>(jsonList)
    println(decodedList)
}
```

As result deserialization of such json fails.

I tried to verify that it's not Kotlin-specific issue but annotation processor seem to fail to produce working for for `InterfaceTest` test. I created searate issue for it https://github.com/ngs-doo/dsl-json/issues/191

PS. It also seems like dsl-json can't handle Kotlin's inline classes but I'll create separate ticket for it.

**Comment by zapov** [comment]
Without trying to run it, I would assume because type param is lost the way you pass that object around.
Try passing explicit type parameter into encoder

**Comment by unoexperto** [comment]
@zapov Are you saying to do something like this ?

```
    val writer = mapper.newWriter()
    mapper.serialize(writer, jsonTypeRef<List<Base2>>().type, testList)
    val bytes = writer.toByteArray()
    val str = String(bytes)
```

Still no discriminator :(

**Comment by zapov** [comment]
Yes, something like that.

Can you try to see if you get discriminator if you make it as a property of some other pojo?

**Comment by zapov** [comment]
So.. it was working as a property.
I've fixed it in latest commit. It should work now if you pass in explicit signature
https://github.com/ngs-doo/dsl-json/blob/master/tests-kotlin/src/test/java/com/dslplatform/json/InheritanceTest.java#L40

**Comment by zapov** [comment]
v1.9.7 released
