### ISSUE TITLE
NonNull annotation issue 

### ISSUE THREAD

**Issue by prasannajoshi2121** [ngs-doo/dsl-json#193]
Hi @zapov 

While waiting for 1.9.7 , i was testing another scenario where i found below error.

NonNull annotation is not working properly on Fields with  @JsonProperty annotation.
But its working fine with DSL's  @JsonAttribute annotation.

import com.dslplatform.json.*;
import com.dslplatform.json.NonNull;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@ToString
@Getter
@Setter
@CompiledJson
public class PrivateSetterNonNull {

  @JsonProperty(value = "test_string")// not working
   //  @JsonAttribute ( working fine , i mean not compilation issues)
  @NonNull
  private String testString;
}

while compiling ,  getting following error 

method setTestString in class com.dsltest.PrivateSetterNonNull cannot be applied to given types;
[ERROR] required: java.lang.String
[ERROR] found: no arguments
[ERROR] reason: actual and formal argument lists differ in length 

let me know if you need more details on this.

**Comment by zapov** [comment]
I'll look. Can you try using some other non null markers instead?

**Comment by prasannajoshi2121** [comment]
sure , actually while testing issue https://github.com/ngs-doo/dsl-json/issues/194 , i found this so thought of letting you know in case in future if someone face similar issue ( Hopping that i am not the one at least :) )

**Comment by zapov** [comment]
Fixed this in latest commit

**Comment by prasannajoshi2121** [comment]
working 👍 , closing issue.
