### ISSUE TITLE
Custom Annotations on fields

### ISSUE THREAD

**Issue by rodneygp** [ngs-doo/dsl-json#197]
We use JSR380 to validate created beans. This requires me to add annotations like
@PositiveOrZero
@NotNull

and so on bean fields. However, this leads to compilation errors in generated code like this:
java: no annotations are allowed in the type of a class literal

How can I avoid this? I found just a solution to allow unknown types, but I feel this is not what I need, as the type is known (I implemented custom converters for my types.

**Comment by zapov** [comment]
I'm not sure I follow the question/problem.
Can you post a class example which is causing problems?

**Comment by rodneygp** [comment]
> I'm not sure I follow the question/problem.
> Can you post a class example which is causing problems?

Sure.

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.PositiveOrZero;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@CompiledJson(onUnknown = CompiledJson.Behavior.IGNORE, name = "NEW_CHANNEL_CREATED_EVENT", discriminator = "messageType")
public class NewChannelCreatedEvent extends AbstractChannelWithPostCountersEvent {
	@NotNull
	private String name;
	private String prefix;
	@NotNull
	private boolean muted;
	@PositiveOrZero
	private long rank;
}

**Comment by zapov** [comment]
There are some improvements now on master.
It should be improved some more, but your example should work now.

**Comment by rodneygp** [comment]
> There are some improvements now on master.
> It should be improved some more, but your example should work now.

Waw! Cool! Hvala vam puno!
Do you expect to have a release in the near future with this improvements?

**Comment by zapov** [comment]
I'll release it before years end.
It would be good if this was tested for a bit before I release it :)

**Comment by rodneygp** [comment]
> I'll release it before years end.
> It would be good if this was tested for a bit before I release it :)

Ok. We'll try to test it and will try to provide feedback. Thanks!

**Comment by zapov** [comment]
v1.9.8 released
