### ISSUE TITLE
Custom json writer

### ISSUE THREAD

**Issue by MTigra** [ngs-doo/dsl-json#198]
Hi. How can I make dsl-json to serialize LocalDateTime in desired format?
Now  it formatting it like this:
```
2020-12-14T13:52:57.327543
```
But we want to format all Localdatetimes like this:
```
2020-12-14T13:52:57.327
```
Probably, i need custom JsonWriter.WriteObject<LocalDateTime> so i create my own class implementing WriteObject interface
But when i do registerWriter(LocalDateTime.class, mylocaldatetimeWriter) it simply ignore it and keep old formattimg way.

**Comment by zapov** [comment]
I think that should work, but you can certainly try to do it explicitly for all such types: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L182

**Comment by zapov** [comment]
This should already work. Reopen with more info if you need extra help
