### ISSUE TITLE
Proguard rules issue

### ISSUE THREAD

**Issue by mecoFarid** [ngs-doo/dsl-json#199]
> DSL-JSON version: 1.9.3
> Platform: Android (Kotlin)

Adding the following rules to the proguard will keep all files including files annotated with DSL-JSON annotations which is expected behavior.

```
-keep class * {
    public private *;
}
```

But using any of proguard content provided in this sample project won't keep files annotated with DSL-JSON annotations. Rules provided in the sample:

```
-keep class dsl_json.json.** { *; }
-dontwarn com.dslplatform.json.**
-keep @com.dslplatform.json.CompiledJson class *
-keep @com.dslplatform.json.JsonConverter class *
```

**Comment by zapov** [comment]
Tnx. I'll look into it/change it

**Comment by zapov** [comment]
I'm assuming something like

    -keep class *_DslJsonConverter { *; }

should also work?
