### ISSUE TITLE
Compiling @CompiledJson classes on non-Windows machines

### ISSUE THREAD

**Issue by ryanpersaud** [ngs-doo/dsl-json#20]
Using the instructions outlined in this SO post:
http://stackoverflow.com/questions/37022606/dsl-json-compiledjson-bean-instantiation-error

I was able to build my project on a Windows machine by manually downloading dsl-compiler.exe.  However, this compiler is a Windows-specific binary.  How would I go about building my project on a non-Windows system?  Thanks.

**Comment by jamespedwards42** [comment]
If you are okay with installing Docker, this project builds on any system that has Docker installed: [github.com/client-side/bitnodes-java-client](https://github.com/client-side/bitnodes-java-client#developer-builds).

**Comment by zapov** [comment]
It's actually a .NET binary, which means if you have Mono on non-Windows system it should work out of the box.

**Comment by zapov** [comment]
@ryanpersaud did you got it working?

**Comment by ayanamist** [comment]
My company has specific CI machines which only runs Linux with JDK and other GCC stuffs, can not ssh into it to run docker or install mono.
Can this .NET binary be translated to java so that it can run in pure java environment?

**Comment by zapov** [comment]
Well, yes it could be translated into Java and it is something I could do, just I don't really have time to do it.

I would be glad if others contributed such stuff, but unless I get contracted to do it (or something along those lines), it's not really likely happening any time soon.

**Comment by zapov** [comment]
Databinding now works without .NET/Mono with comparable performance: https://github.com/ngs-doo/dsl-json/tree/master/examples/MavenJava8
