### ISSUE TITLE
Unable to deserialize more complex type hierarchies with generics using reflection

### ISSUE THREAD

**Issue by schernic** [ngs-doo/dsl-json#201]
Trying to deserialize objects of classes with more complex type hierarchies and generics using reflection fails with exceptions claiming that readers for type parameters were not found.

Even simple cases like using setters for bounded type parameters fail.

Example Test case: 
```
public static class ClassExtendingClassWithBoundTypeParameter extends ClassWithBoundTypeParameter<String> {
}

public static class ClassWithBoundTypeParameter<T extends String> {

     private T[] property;

     public T[] getProperty() {
         return property;
     }

     public void setProperty(T[] property) {
        this.property = property;
     }
}

@Test
public void checkBoundTypeParameter() throws IOException {
   byte[] bytes = "{\"property\":[\"abc\"]}".getBytes("UTF-8");
   ClassExtendingClassWithBoundTypeParameter deser = json.deserialize(ClassExtendingClassWithBoundTypeParameter.class, bytes, bytes.length);
   Assert.assertArrayEquals(new String[]{"abc"}, deser.getProperty());
}    
```

Please have a look at PR https://github.com/ngs-doo/dsl-json/pull/202 for a fix.

**Comment by zapov** [comment]
Tnx for the PR.
I'll take a look when quakes calm down a bit :)

**Comment by zapov** [comment]
This now also works with annotation processor.
Will look into making a new release next week.

**Comment by zapov** [comment]
v1.9.8 released
