### ISSUE TITLE
Deserialization and serialization for @JsonFormat(shape = JsonFormat.Shape.OBJECT)

### ISSUE THREAD

**Issue by prasannajoshi2121** [ngs-doo/dsl-json#203]
Hi @zapov , 

I am having Enum like below 
```
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
@AllArgsConstructor
@Getter
@CompiledJson
public enum TestEnum {
  ONE("one", "xyz", "name_1", 0),
  TWO("two", "abc", "name_2", 1);

  @JsonProperty("test_type")
  private String type;

  @JsonProperty("test_code")
  private String code;

  @JsonProperty("test_name")
  private String name;

  @JsonProperty("test_count")
  private int count;

}
```
is it possible serialize above Enum to something like below Json , both single object and list type and deserialize it back to Enum (single and list) ?
Jackson does using this using above mentioned annotation - @JsonFormat(shape = JsonFormat.Shape.OBJECT)
 
 attached sample enum class with test case which is not serializing properly(TestSimpleEnum.java) 
[dslissue.zip](https://github.com/ngs-doo/dsl-json/files/5772350/dslissue.zip)

Expected single Object : 

{
        "test_type": "one",
        "test_code": "xyz",
        "test_name": "name_1",
        "test_count": "0"
}

Expected Arraylist :

[
    {
        "test_type": "one",
        "test_code": "xyz",
        "test_name": "name_1",
        "test_count": "0"
    },
    { 
        "test_type": "two",
        "test_code": "abc",
        "test_name": "name_2",
        "test_count": "1"
    }
]

**Comment by zapov** [comment]
You can implement JsonObject on that enum and provide custom serialize + deserialize implementation.
It is not as nice as just putting annotations like in Jackson.

Alternatively you can use JsonConverter(target = TestEnum.class)

But both will require some manual setup or proxying to another class with expected structure

**Comment by prasannajoshi2121** [comment]
I was wondering if manual implementation would slow us down during serialization and deserialization ?

**Comment by zapov** [comment]
Not if you follow the same patterns as generated code.
You can also get a small speedup here if you precalculate the objects and store them into byte[].
Then you can use `writer.writeAscii` (or something alike) to just push them down.
As for deserialization, that could be nontrivial code depending on how much validation you want there, but if you don't need that much and can use one field as an identifier, you should be able to get quite close perf to plain vanilla enum deserializer.

**Comment by prasannajoshi2121** [comment]
sure let me try this and see if that works , keeping defect open for more discussion :)

**Comment by prasannajoshi2121** [comment]
@zapov if possible could you please provide me example of converting JsonArray into java List type using custom convertor .
Like i am trying to write custom converter but the reader object is of single Object return type  and not List

public static final JsonReader.ReadObject<CustomEnumType> JSON_READER_OBJECT = new JsonReader.ReadObject<CustomEnumType>() {
            public CustomEnumType read(JsonReader reader) throws IOException {
                return CustomEnumType.Type1;
            }
        };
        
        and was thinking to use like below
            List<CustomEnumType> deser = dslJsonList.deserializeList(CustomEnumType.class, buffer, buffer.length);
            
           please let me know if this approach is correct ?

**Comment by zapov** [comment]
You only need to write converter for object. List of those objects should be normally resolved then (as long as list analyzer is enabled - which is by default, although you can do it explicitly)

https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L39

https://github.com/ngs-doo/dsl-json/blob/master/java8/src/main/java/com/dslplatform/json/runtime/Settings.java#L192

**Comment by prasannajoshi2121** [comment]
Hi @zapov 
thanks for quick response , also I see @JsonIgnore is broken and no longer working , let me know if you need any sample example to reproduce . I am using 1.9.7 version.

**Comment by zapov** [comment]
Please provide an example/test of where its broken, as I'm not aware of it

**Comment by prasannajoshi2121** [comment]
sample pojo

```@AllArgsConstructor
@NoArgsConstructor
@ToString
@Getter
@Setter
@CompiledJson
public class PrivateSetter{

  @JsonProperty(value = "test_string")
  private String testString;

  @JsonIgnore
  private String str;
}
```
sample test :

```
DslJson<Object> dslJsonList = new DslJson<>(Settings.basicSetup());
PrivateSetter deser = new PrivateSetter();
    deser.setTestString("test");
    deser.setStr("ignore");
    ByteArrayOutputStream ba = new ByteArrayOutputStream();
    dslJsonList.serialize(deser, ba);
    Assert.assertEquals("{\"test_string\":\"test\"}",ba.toString());
    
    output : 
    Expected :{"test_string":"test"}
Actual   :{"test_string":"test","str":"ignore"}

same test working with ObjectMapper :
    ObjectMapper mapper = new ObjectMapper();
    PrivateSetter deser = new PrivateSetter();
    deser.setTestString("test");
    deser.setStr("ignore");
    Assert.assertEquals("{\"test_string\":\"test\"}",mapper.writeValueAsString(deser));
    
 

```

**Comment by zapov** [comment]
Ah, this actually never worked. It will work if you put it on public getter.
I'll look if its easy to support it, but you might be maybe able to get it to work if you instruct Lombok to copy it onto getter

**Comment by zapov** [comment]
v1.9.8 released. This private JsonIgnore should work now
