### ISSUE TITLE
Close converter

### ISSUE THREAD

**Issue by markebbers** [ngs-doo/dsl-json#205]
I have a question about the following;

Is it possible that a converter get notified when the reader is done? This to remove / clear static state.

And how can I register a converter, not for a type but just for 1 single field, which is a basic type. This by using a converter-factory because my converter has state (caches).

**Comment by zapov** [comment]
Your question does not make too much sense to me. Converter calls into reader, so it knows when reader is done.
You will have to explain it in bit more detail.

As for the converter on a single field you can use this: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L40

ThreadLocal should work fine with DSL-JSON
