### ISSUE TITLE
Read object as JSON string 

### ISSUE THREAD

**Issue by markebbers** [ngs-doo/dsl-json#206]
I'm implementing a JsonReader which will read a lot of duplicate objects. So I had the idea to cache the whole JSON string to improve performance. How can I do that?

For example:
```json
ObjectA {
  "field1" = "a",
  "field2" = "b"
}
```

Read this as String, check my cache if there is already an existing instance. (Map<String, ObjectA>). If not parse the json string to object.

**Comment by zapov** [comment]
There is no concept of whole JSON string caching in DSL-JSON.

There is concept of string caching so you can leverage that to avoid string allocations: https://github.com/ngs-doo/dsl-json/blob/2ac05245ac20479a3fe9a31e5754da6a29c38d74/library/src/main/java/com/dslplatform/json/StringCache.java
The other thing you can do is use factories and cache object instances in there: https://github.com/ngs-doo/dsl-json/blob/2ac05245ac20479a3fe9a31e5754da6a29c38d74/examples/ArrayFormat/src/main/java/com/dslplatform/array/Example.java#L126
