### ISSUE TITLE
Lenient parsing

### ISSUE THREAD

**Issue by markebbers** [ngs-doo/dsl-json#207]
Is it possible to use less strict (lenient) parsing with dsl-json? This to directly parse non strings into string. For example read a double value as string.

For example I want to parse this snippet of JSON directly to the given class. 
```json
{
  "currency": "EUR",
  "amount": 49.99
}
```
```kotlin
data class (val currency: String, val amount: String)
```

**Comment by zapov** [comment]
You should be able to do it via property converter, eg: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L40
For example parse it as big decimal (or something alike) and then return string

**Comment by markebbers** [comment]
Thanks for your reply and I already did exactly the same :smile:. But this still introduces some extra parsing steps. So maybe this lenient might be a nice to have feature in the future.

**Comment by zapov** [comment]
What do you mean by extra parsing steps? Can you show it in code?

**Comment by markebbers** [comment]
> What do you mean by extra parsing steps? Can you show it in code?

What I mean is that you need to construct a BigDecimal object and then call the toPlainString() just the get the same string value as if you just red it as string. And in my use-case I have 10th of millions of these objects so this BigDecimal construction will impact performance.

**Comment by zapov** [comment]
Ah, ok.
But you can just write relevant code for parsing this. Eg if you look at parse numbers code at the start you have:

    final int start = reader.scanNumber();
    final int end = reader.getCurrentIndex();
    final byte[] buf = reader.buffer;

Assuming that you are parsing of byte[] instead of stream.
Then you can create string from buffer and start/end info.

So there is no real use case for this in library, but sure it would be nice to have something like that in the examples.

**Comment by markebbers** [comment]
> Ah, ok.
> But you can just write relevant code for parsing this. Eg if you look at parse numbers code at the start you have:
> 
> ```
> final int start = reader.scanNumber();
> final int end = reader.getCurrentIndex();
> final byte[] buf = reader.buffer;
> ```
> 
> Assuming that you are parsing of byte[] instead of stream.
> Then you can create string from buffer and start/end info.
> 
> So there is no real use case for this in library, but sure it would be nice to have something like that in the examples.

Thanks for your fast response and looking good! Is this also usable if I use a stream?

**Comment by zapov** [comment]
You need some more edge case handling in the case, but you can see it there in the parsing code, eg:

    if (end == reader.length()) {
        final NumberInfo tmp = readLongNumber(reader, start);
        return parseFloatGeneric(tmp.buffer, tmp.length, reader, false);
    }

where you could use that tmp for the same purpose. Or if you want to go crazy avoid even that allocation by inlining code there.

**Comment by markebbers** [comment]
Thanks, I will dive into that. Most of the methods and objects you mention are (package) private members of NumberConverter.

**Comment by markebbers** [comment]
I followed your advice but found at that parsing it to the BigDecimal directly is already very fast :) Thank you for your support.
