### ISSUE TITLE
Need public some methods in library

### ISSUE THREAD

**Issue by longdt** [ngs-doo/dsl-json#209]
while we have some public methods: `DslJon.serialize()` which accepts `JsonWriter` as input but following method:  `DslJon.deserialize()` was declared as private modify
```
	@SuppressWarnings("unchecked")
	@Nullable
	private <TResult> TResult deserialize(
			final Class<TResult> manifest,
			final JsonReader json,
			final InputStream stream) throws IOException {
```
while `JsonWriter.reset()` was declared as public method but JsonReader.reset() was private so we can't reset reader to reuse
Pls make these methods as public

**Comment by zapov** [comment]
Not sure about making it public, but we could certainly make it protected. Would that be sufficient?

**Comment by zapov** [comment]
v1.10 released
