### ISSUE TITLE
JsonWriter Usage

### ISSUE THREAD

**Issue by jamespedwards42** [ngs-doo/dsl-json#21]
I've been using the [JsonWriter(byte[]) constructor with a ThreadLocal](https://github.com/client-side/bitnodes-java-client/blob/master/dsljson-model/src/engineering.clientside.bitnodes_dsljson_model/java/engineering/clientside/bitnodes/DslJsonBitnodesCoder.java#L45).  I just noticed all of the JsonWriter constructors are package private now.  What is the best practice?

**Comment by jamespedwards42** [comment]
I've changed it use DslJson#newWriter.  Is there no advantage to having a factory method that accepts a re-used byte[] buffer or desired buffer size?

**Comment by zapov** [comment]
In most scenarios you are probably better off with caching of JsonWriter which will accommodate it's internal buffer to appropriate size. But you are right... I should have created factory method which accepts a (byte[], int) also.
I will add that in next version, but scenarios where that is really useful should be rare.
JsonWriter will create a new buffer if one originally provided is not sufficiently large.
