### ISSUE TITLE
Variable is already defined in class ObjectFormatConverter

### ISSUE THREAD

**Issue by mecoFarid** [ngs-doo/dsl-json#211]
**Library Version:** 1.9.4
**Platform:** Android

Whenever subclass overrides and defines a new name for a public field from the superclass, the project fails to compile.

**SuperClass**

```
@CompiledJson
public class SuperClass {
    public String field;

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }
}
```

**ChildClass**
```

@CompiledJson
public class ChildClass extends SuperClass{
    @JsonAttribute(name = "named_fields")
    @Override
    public String getField() {
        return super.getField();
    }
}
```

**Error:**
> variable quoted_field is already defined in class ObjectFormatConverter

Once "field" is converted to a private or package-private field in `SuperClass`, the project compiles.

**Comment by zapov** [comment]
Tnx for the bug report. I'll look what can be done about this

**Comment by zapov** [comment]
I've pushed a fix for this in latest commit: https://github.com/ngs-doo/dsl-json/commit/9fd005c75be71c9ea2c714495022242f462a451c

**Comment by zapov** [comment]
v1.9.9 released
