### ISSUE TITLE
JsonReader and ByteBuffer

### ISSUE THREAD

**Issue by TeofilisMartisius** [ngs-doo/dsl-json#219]
Hello,

Are there any plans to modify JsonReader to work with ByteBuffers?

I have some code which uses ByteBuffers, and they cannot be converted to byte arrays (memory mapped byte buffers). I would like to be able to read ByteBuffers using DslJson JsonReader without having to allocate more objects.

I would be willing to contribute some of my time to make changes myself. But I don't see any easy way to do this unless a completely new JsonReader implementation is created as current one is quite strongly tied to a byte array. I guess current JsonReader class can stay as facade and delegate to either ByteArrayJsonReader or ByteBufferJsonReader under the hood keeping the interface the same...

Sincerely,
Teofilis Martisius

**Comment by plokhotnyuk** [comment]
@TeofilisMartisius ByteBuffers are slower when accessing them byte per byte comparing to byte arrays, so it is worth having an internal pre-allocated buffer with some copying.

[Here](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-core/jvm/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala) you can see how jsoniter-scala uses an internal buffer to avoid allocations for solving the same problem.

**Comment by zapov** [comment]
Hi,

there are no plans. As @plokhotnyuk mentioned, there is noticeable overhead of using byte buffers, so a better pattern would be to also have byte[] around which you can use for such purpose.

**Comment by TeofilisMartisius** [comment]
Hello,

Thanks for the ideas! Yes, I can allocate a byte array and just copy the data from byte buffer- it's doesn't stress GC if I keep the byte array, and it's fast enough for me. In fact I've already modified my code to do it.

I'll close this ticket. Thanks for very very quick response.

Sincerely,
Teofilis Martisius
