### ISSUE TITLE
 Unable to find matching property in Kotlin data class fields start with "is" 

### ISSUE THREAD

**Issue by Rufim** [ngs-doo/dsl-json#225]
Lib Version 1.9.9

When i try compile project with this class:
```
@CompiledJson
data class Result(
    val isLocked: Boolean, 
    val id: String? = null,
    val token: String? = null,
)
```
I get following error: Unable to find matching property: 'isLocked' used in constructor. Either use annotation processor on source code, on bytecode with -parameters flag (to enable parameter names) or manually create an instance via converter
           
For any fields with "is" i also got this error

Any ideas how to fix it?

**Comment by zapov** [comment]
Tnx for the bug report.

For now the best thing you can do (assuming you want isLocked in JSON output) is to have something like
```
        @JsonAttribute(name = "isLocked")
    val locked: Boolean,
```

**Comment by zapov** [comment]
I fixed this not to break, but it will encode property as isLocked
If you want to encode it as locked it will need to have 

    @JsonAttribute(name = "locked")

I'm not actually sure if this is the best way to go about this, as this way you can do

    ctor(boolean locked)

and

    ctor(boolean isLocked)

to control the actual name of JSON attribute. And it seems more natural to use exact argument names from Kotlin

**Comment by zapov** [comment]
v1.10 released
