### ISSUE TITLE
The example is not working

### ISSUE THREAD

**Issue by BillowGY** [ngs-doo/dsl-json#227]
Hi there,
I loaded the project MavenJava8 in eclipse, then compile and tried to run Example which give me exception like:
**```
_Exception in thread "main" com.dslplatform.json.ConfigurationException: Unable to serialize provided object. Failed to find serializer for: class com.dslplatform.maven.Example$Model
	at com.dslplatform.json.DslJson.serialize(DslJson.java:2905)
	at com.dslplatform.maven.Example.main(Example.java:264)_
```**
Then I run it using mvn which gave me same error:

mvn exec:java -Dexec.mainClass="com.dslplatform.maven.Example"
**_```
>mvn exec:java -Dexec.mainClass="com.dslplatform.maven.Example"
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< com.dslplatform:maven-java8-example >-----------------
[INFO] Building maven-java8-example 1.9.9
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ maven-java8-example ---
[WARNING]
com.dslplatform.json.ConfigurationException: Unable to serialize provided object. Failed to find serializer for: class com.dslplatform.maven.Example$Model
    at com.dslplatform.json.DslJson.serialize (DslJson.java:2905)
    at com.dslplatform.maven.Example.main (Example.java:264)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.346 s
[INFO] Finished at: 2022-03-24T10:41:20-07:00
[INFO] ------------------------------------------------------------------------
```_**

If I delete the target folder created by Eclipse, then run "mvn exec:java -Dexec.mainClass="com.dslplatform.maven.Example""
it worked fine.

Do you know what's wrong? 
**openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)**

**Comment by BillowGY** [comment]
checked and eclipse didn't create classes like:
_Example$Model$Abstract_DslJsonConverter.class
......
_Example$Model_DslJsonConverter$ObjectFormatConverter.class
_Example$Model_DslJsonConverter.class

If I copy these missing classes to the target/classes.../maven folder, then I can run Example in eclipse

**Comment by BillowGY** [comment]
I can run mvn compile in eclipse to have it work. But this is not what want to manually do. It's not flexible.

**Comment by zapov** [comment]
I don't really use Eclipse much, but I'm assuming you just need to setup Annotation Processors in there.
Something like: https://stackoverflow.com/questions/43404891/how-to-configure-java-annotation-processors-in-eclipse

**Comment by BillowGY** [comment]
thanks. If it needs manually setup, then I may not use it. It's not convenient when you have lots of developers in the team.
