### ISSUE TITLE
method readBase64() of JsonReader

### ISSUE THREAD

**Issue by imrafaelmerino** [ngs-doo/dsl-json#232]
The method returns an empty array of bytes reading a string that is not base64.

The same result is returned when an empty string is read, which is ok.

""    -> [].   (ok)
"a". -> [].    (NOT ok, "a" is not a valid base64 string, cannot be decoded)

it makes hard to the client distinguish errors from the corner case (empty string). In other cases a ParsingException is thrown whenever the reader finds an error.

Not sure if it's working as expected...

**Comment by zapov** [comment]
It would be good to improve it and throw errors for invalid base64.
I dont have much time to improve it ATM. It would be great if someone makes a PR to improve it.

**Comment by zapov** [comment]
This is now parsed as expected. Added a test for this. Not sure if there are other cases.

**Comment by zapov** [comment]
v1.10 released
