### ISSUE TITLE
By `char` reading from `String` at `JsonReader`

### ISSUE THREAD

**Issue by catap** [ngs-doo/dsl-json#235]
Hey,

This is more than an idea, not a bug: `DslJson.newReader(String)` might be improved if `JsonReader` supports reading from strings by `char` via `charAt(int)`.

Such API allows to parse strings in much more GC friendly way, without `toByte()` which copies strings.

**Comment by zapov** [comment]
There wouldn't be any benefit to it as the entire library works with bytes not chars.
This API is deprecated as a way to discourage users from trying to pass in strings.
If you want to reduce GC, try to pass bytes or streams for processing instead of optimizing GC for strings.
