### ISSUE TITLE
Any plans to support Jakarta JSON-B(JSR 367)

### ISSUE THREAD

**Issue by doukai** [ngs-doo/dsl-json#236]
Any plan or idea about to support it?
[https://jakarta.ee/specifications/jsonb/3.0/jakarta-jsonb-spec-3.0.html](url)
[https://javaee.github.io/jsonb-spec/](url)
Thank!

**Comment by zapov** [comment]
No such plans ATM :(

It would be nice to have it eventually.
For now there is only simple support: https://github.com/ngs-doo/dsl-json/tree/master/examples/Jsonb

**Comment by doukai** [comment]
Maybe it's too early, thanks for your answer
