### ISSUE TITLE
Manually create META-INF/services file

### ISSUE THREAD

**Issue by nanders4** [ngs-doo/dsl-json#237]
Hi,
Because of some issues with my build system, the META-INF/services file is not making it into my build, causing DslJson to complain.
I read that this file can be provided manually. Could you provide the format of the Configuration file?
Say we have a situation like below:

```
@CompiledJson(discriminator = "@type")
public abstract class AbstractClass {
}

@Data
@CompiledJson(name = "ImplClass")
public class ImplClass extends AbstractClass {
		private final int number;
		private final String name;
}
```

What should be in the META-INF/services/...Configuration file to make this work?

**Comment by zapov** [comment]
META-INF is not the primary discovery mechanism for years now.
DSL-JSON will look into specific package name first: `dsl_json.your_package.YourClassConverter`

So you should check if this file gets created or fix the problem causing it not getting created.
In the end, you can use META-INF later to load up all such dependencies up-front, but this doesn't seem like your issue.

You have gradle example here: https://github.com/ngs-doo/dsl-json/blob/master/examples/AndroidJava/app/build.gradle#L42
As for your question, META-INF just lists relevant converter files (or just a single one which loads up all the others)
