### ISSUE TITLE
Unable to serialize valid json object

### ISSUE THREAD

**Issue by mandeepjain** [ngs-doo/dsl-json#238]
Json : 

`{"id":"77abbb7c-cdee-4259-8828-f6681e2ea3b1","identity":20317609,"type":"profile","profileData":{"displayName":"familiar_farfetch’d99","language":"english"}}`

Error : 

> com.dslplatform.json.ParsingException: Unexpected end of JSON input
> 	at com.dslplatform.json.ParsingException.create(ParsingException.java:23) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.JsonReader.read(JsonReader.java:324) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.JsonReader.getNextToken(JsonReader.java:849) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.ObjectConverter.deserializeMap(ObjectConverter.java:106) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.ObjectConverter.deserializeObject(ObjectConverter.java:77) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.ObjectConverter.deserializeMap(ObjectConverter.java:109) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.ObjectConverter$2.read(ObjectConverter.java:20) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.ObjectConverter$2.read(ObjectConverter.java:16) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.DslJson.deserialize(DslJson.java:1551) ~[dsl-json-1.9.5.jar:?]

> Caused by: java.io.EOFException
> 	at com.dslplatform.json.JsonReader.<clinit>(JsonReader.java:306) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.DslJson$2.initialValue(DslJson.java:488) ~[dsl-json-1.9.5.jar:?]
> 	at com.dslplatform.json.DslJson$2.initialValue(DslJson.java:485) ~[dsl-json-1.9.5.jar:?]
> 	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180) ~[?:1.8.0_292]
> 	at java.lang.ThreadLocal.get(ThreadLocal.java:170) ~[?:1.8.0_292]
> 	at com.dslplatform.json.DslJson.deserialize(DslJson.java:1546) ~[dsl-json-1.9.5.jar:?]
> 	at in.gameskraft.missionservice.utils.EventUtil.enrichCasualEvents(EventUtil.java:26) ~[classes/:?]

Can you please help @zapov

**Comment by mandeepjain** [comment]
On further exploring, library is failing when there are special characters present.

Ex : 
```
familiar_farfetch’d99
nizam’s_whistle
early_atlético106
reduced_farfetch’d44
```

**Comment by zapov** [comment]
I tried reproducing it on master but it works for me :/

Pls try on latest version and ideally make a PR with failing test

**Comment by mandeepjain** [comment]
I have raised a PR, kindly look into it
#239

**Comment by zapov** [comment]
The problem you are experiencing is non UTF-8 encoding.

This works as expected

    byte[] data = jsonWriter.toString().getBytes(StandardCharsets.UTF_8);
    Map res = json.deserialize(Map.class, data, data.length);
    Assert.assertEquals(root.get("displayName"), res.get("displayName"));

**Comment by mandeepjain** [comment]
Thank you for the response
