### ISSUE TITLE
Disabling including of type information during serialization

### ISSUE THREAD

**Issue by dcrn** [ngs-doo/dsl-json#24]
I'm currently using dsl-json in an API server. We have several types of response messages with different parameters, all of which implement the `Response` interface. I believe type information is included automatically because we're using an abstract type, but I'm looking for some way to disable that.

```
@CompiledJson
public class ApiOutput {
    public Response data;
    public Integer status_code;
    ....
}

@CompiledJson
public class ResultResponse implements Response {
    public String result = "success";
}
```

The output JSON of serialization:
```
{
    "data": {
        "$type": "responses.ResultResponse",
        "result": "success"
    },
    "status_code": 200,
    ...
}
```

Is there some way to disable the `$type` field during serialization? Maybe some annotation parameter?

**Comment by zapov** [comment]
Not currently.
I'll have to take a look what can be done about it.

**Comment by zapov** [comment]
What you currently can do is implement `JsonObject` on `ApiOutput` (if it's not too large) and write manual serialization code where you serialize the actual type instead of interface. Then no $type will end up in that object.

**Comment by dcrn** [comment]
Thanks for the quick reply! I'll try that for now, but I'm expecting more abstract types later.
Cheers.

**Comment by zapov** [comment]
I've released a new version. Now you can disable $type attribute by configuring annotation: https://github.com/ngs-doo/dsl-json/blob/master/examples/Maven/src/main/java/com/dslplatform/maven/Example.java#L24
