### ISSUE TITLE
Support kotlin inline classes

### ISSUE THREAD

**Issue by vans239** [ngs-doo/dsl-json#244]
Kotlin has a nice feature [inline classes](https://kotlinlang.org/docs/inline-classes.html).
Let's assume that we have a class which stores a price in cents (2 digits precision)
Currently I do something like (quite hacky), but it causes long boxing:
```
@JvmInline
value class Decimal2(val raw: Long)

class Event {
    @JsonAttribute(converter = Decimal2Converter.RawConverter::class)
    @set:JvmName("price")
    @get:JvmName("price")
    var price: Decimal2 = DEC2_ZERO
}
```
Input json example: `{"price": 1.29}`, would be transformed into `Decimal(129)`

It would be nice to have first-citizen support for kotlin inline classes

**Comment by zapov** [comment]
You can define converter for a type instead on a property?
How that class looks from Java? It will be easier to reason if I understand what types are used around.
Are you trying to get away from allocating decimal2 class or? You can technically do that via thread locals.

**Comment by vans239** [comment]
Kotlin inline classes is a syntax sugar around "underlying" types. For example `value class Dec2(private val raw: Long)` in the bytecode in most cases will be just Long.

Larger example
Kotlin code:
```
@JvmInline
value class Dec2(private val raw: Long) {
    fun plus(other: Dec2) = Dec2(raw + other.raw)

    override fun toString() = "${raw / 100}.${raw % 100}"
}

fun main() {
    println(Dec2(100).plus(Dec2(250)))
}
```
transforms to bytecode equal to (omitted boilerplate):
```
public final class Dec2 {
   private final long raw;

   @NotNull
   public String toString() {
      return toString-impl(this.raw);
   }
   private Dec2(long raw) {
      this.raw = raw;
   }

   public static final long plus_TBQ2tDQ/* $FF was: plus-TBQ2tDQ*/(long $this, long other) {
      return constructor-impl($this + other);
   }

   @NotNull
   public static String toString_impl/* $FF was: toString-impl*/(long $this) {
      return "" + $this / (long)100 + '.' + $this % (long)100;
   }

   public static long constructor_impl/* $FF was: constructor-impl*/(long raw) {
      return raw;
   }

   public static final Dec2 box_impl/* $FF was: box-impl*/(long v) {
      return new Dec2(v);
   }

   public final long unbox_impl/* $FF was: unbox-impl*/() {
      return this.raw;
   }
}

public final class ExampleKt {
   public static final void main() {
      String var0 = Dec2.toString-impl(Dec2.plus-TBQ2tDQ(Dec2.constructor-impl(100L), Dec2.constructor-impl(250L)));
      System.out.println(var0);
   }
}
```

Important detail that `Dec2` object is not allocated. We still have only Long , just with nice API.

**Comment by vans239** [comment]
> You can define converter for a type instead on a property?
That's exactly how I do now (see example from my initial comment)
> Are you trying to get away from allocating decimal2 class or? 
I am trying to avoid primitive boxing (which is caused by converters). I also can not use default primitive parsers because my type has special semantics ( "123.45" is equal to Dec2(12345)).
> You can technically do that via thread locals.
I'd need pool of such objects, which is probably possible, but sounds overcomplicated. Most likely it will not be better than garbage collector

**Comment by zapov** [comment]
I was actually asking how the Event class looks as I have a feeling if Dec2 is used as signature around, there will certainly be some conversion and allocation.

Custom converters for primitive is nice. I kind of hope this would start working out of the box with Java improvements, but can certainly give it some thought how to implement this currently.

As for converter, I was thinking you need pool, just a thread local variable which you will pass around (assuming that this really works through underlying value and not by keeping reference to this object instance).

Eg if this was actually just a signature wrapper I would guess this should be enough

class Dec2(var raw: long)

and then instead of keeping reference to Dec2 just read raw during assignment... eg 


    class Event {
      private long dec2;
      public void setDec2(Dec2 arg) {
        dec2 = arg.raw;  
      }
    }

But I'm assuming it doesnt work like that, but actually uses this object references around and you can't really mutate this Dec2 objects are it uses vals instead of vars

**Comment by vans239** [comment]
> I was actually asking how the Event class looks as I have a feeling if Dec2 is used as signature around, there will certainly be some conversion and allocation.

Let's assume 
```
class Trade(var price: Dec2, var quantity: Dec2, var timestamp: Long)
```
So ideally I'd like to reuse same object (using `bind` feature).  It would not allocate anything if I used only primitive types

> As for converter, I was thinking you dont need a pool, just a thread local variable which you will pass around (assuming that this really works through underlying value and not by keeping reference to this object instance).

Probably I am not fully following suggestion and most likely I didn't explain root issue well enough.

> But I'm assuming it doesnt work like that, but actually uses this object references around and you can't really mutate this Dec2 objects are it uses vals instead of vars

Dec2 behaves in same way as underlying type. So in my case Dec2 object should not allocate at all.  The only place where allocation happens is `JsonReader.ReadObject` , because it's generic.

**Comment by vans239** [comment]
Probably we can consider different use case and ignore inline classes.
There is no way to define primitive type parsers which would not cause allocations.

Code: `class Trade(var priceInCents: Long, var timestamp: Long)`
Json: `{"price": 123.45, timestamp: 123455678}`
So I can not use long parser and would prefer to avoid double

**Comment by zapov** [comment]
I guess we could expand converter to have alternative way to read/write.
Currently you can do

	@JsonConverter(target = int.class)
	public static abstract class IntConverter {
		public static final JsonReader.ReadObject<Integer> JSON_READER = new JsonReader.ReadObject<Integer>() {
			public Integer read(JsonReader reader) throws IOException {
				return NumberConverter.deserializeInt(reader);
			}
		};
		public static final JsonWriter.WriteObject<Integer> JSON_WRITER = new JsonWriter.WriteObject<Integer>() {
			public void write(JsonWriter writer, Integer value) {
				NumberConverter.serialize(value, writer);
			}
		};
	}

but technically one could also write something like

	@JsonConverter(target = int.class)
	public static abstract class IntConverter {
		public static int read(JsonReader reader) throws IOException {
			return NumberConverter.deserializeInt(reader);
		}
		public static void write(JsonWriter writer, int value) {
			NumberConverter.serialize(value, writer);
		}
	}

I'll look if this is something which can be implemented relatively easily

**Comment by zapov** [comment]
Added support with latest commit. Didnt try it on Kotlin, so do get back if there is some problems there.

**Comment by vans239** [comment]
Link to commit https://github.com/ngs-doo/dsl-json/commit/c1e0c1e260d8f156898a26594d27c17b3b876af8

Yes, I believe that it would work for kotlin also.
I'll give a try!

**Comment by vans239** [comment]
Is there a place where snapshots are published?

**Comment by vans239** [comment]
Minor issue which I faced:
```
error: Specified converter: 'RawConverter' has invalid type for read method. It must be of type: 'long read(com.dslplatform.json.JsonReader)'. Wrong argument defined. Expecting 'com.dslplatform.json.JsonReader'. Detected: 'com.dslplatform.json.JsonReader<?>'
```
Kotlin doesn't allow skipping generic (at least I am not aware), theoretically I can switch to java here.
Anyway check probably should allow `JsonReader<?>`

**Comment by zapov** [comment]
It should be better with last commit.

**Comment by vans239** [comment]
@zapov Is there any way to obtain snapshot version other than publishing it by myself or building locally? Or maybe you would consider releasing the feature?

**Comment by zapov** [comment]
Not really. I don't have time to publish snapshots somewhere :/
I usually just build it locally

**Comment by zapov** [comment]
I plan on making a new release soon. But would much prefer to get rid of known problems before

**Comment by zapov** [comment]
v1.10 released
