### ISSUE TITLE
About json field policy of object

### ISSUE THREAD

**Issue by zhangtianxiao** [ngs-doo/dsl-json#248]
```java
@CompiledJson
class Main{
  private String name = "张三";
  private long id = 21;
  getter ... 
  setter ...

  public static StringBuilder other() {
    return new StringBuilder();
  }
}
```
Main class is marked by @CompiledJson,  then, _Main_DslJsonConverter.java contains a field named 'other'.
This is not appropriate.

**Comment by zapov** [comment]
Sorry, I don't understand what you mean.

**Comment by zhangtianxiao** [comment]
> Sorry, I don't understand what you mean.

The problem is solved by using '@ JsonAttribute' on the 'other' method
