### ISSUE TITLE
Mandatory enum fields cause invalid Java syntax to be generated

### ISSUE THREAD

**Issue by dcrn** [ngs-doo/dsl-json#25]
Using enums with the mandatory attribute seems to cause invalid Java to be generated. I tested with a small sample below:
(dsl-json-processor version 1.4.5)

MyObject.java:
```
import com.dslplatform.json.CompiledJson;
import com.dslplatform.json.JsonAttribute;

@CompiledJson
public class MyObject {
    @JsonAttribute(mandatory = true)
    public MyEnum value;
}
```

MyEnum.java:
```
public enum MyEnum {
    Hello,
    World
}
```

ExternalSerialization.java error lines:
```
	static void __serializeJsonObjectMinimal(final MyObject self, com.dslplatform.json.JsonWriter sw, boolean hasWrittenProperty) {
		
		
		else {
			hasWrittenProperty = true;
			sw.writeAscii("\"value\":null", 12);
		}
	}
```

The inserted "else" here is causing a syntax error during compilation.

**Comment by zapov** [comment]
Tnx for the bug report.
I've deployed a fix to the compiler.

**Comment by zapov** [comment]
Can you confirm this is now working as expected?

**Comment by dcrn** [comment]
Looks like it compiles now, but while testing that I think I found another issue:
```
@CompiledJson
public class TestObject {
    @JsonAttribute(mandatory = true)
    public String opt;

    public static void main(String[] arg) throws IOException {
        String data = "{}";
        TestObject oo = new DslJson<Object>().deserialize(TestObject.class, data.getBytes(), data.length());
        System.out.println(oo.opt);
    }
}
```
This example does not throw an IOException as expected.

**Comment by zapov** [comment]
Ah, right. Some shortcuts are no longer valid now with more features: https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/DslJson.java#L1041
I'll remove those.

**Comment by zapov** [comment]
New version is released. It contains a fix for that issue.

**Comment by dcrn** [comment]
Confirmed working, thanks!
