### ISSUE TITLE
serialize/deserialize Set as a List

### ISSUE THREAD

**Issue by adarcanum** [ngs-doo/dsl-json#254]
Hey, so seems by default dsl json handles `java.util.Set` as an `Object` and is looking for `{`.

In json `{"a", "b", "c"}` is not valid json, one would expect that a `Set` would essentially be treated the same way as `List`.

So one solution that I am currently using is registering a custom converter for `Set` but I can't seem to come up with a solution for generic `Set<T>`. I.e. I have this (kotlin code)

n.b. naturally `MyObject` has `@CompiledJson` annotation

```
object MyObjectSetConverter {
    val JSON_READER: com.dslplatform.json.JsonReader.ReadObject<Set<MyObject>> =
        com.dslplatform.json.JsonReader.ReadObject<Set<MyObject>> { reader ->
            ObjectConverter.deserializeList(reader).map { MyObject(it as String) }.toSet()
        }
    val JSON_WRITER: com.dslplatform.json.JsonWriter.WriteObject<Set<MyObject>> =
        com.dslplatform.json.JsonWriter.WriteObject<Set<MyObject>> { writer, value ->
            dslJson.serialize(writer, value.toList())
        }

    @Throws(IOException::class)
    fun deserialize(reader: com.dslplatform.json.JsonReader<*>): Set<Any>? {
        return JSON_READER.read(reader)
    }
}
```

So for every typed `Set` I would need to implement a converter and then add annotation to each reference in more complex objects. Ideally would be good just to configure dsl json to treat `Set` as `List`. I am struggling to implement a generic solution to treat Set as a List.

Would appreciate a bump in the right direction - potentially would require a PR to add `desiarializeSet` method similar to `deserialzeMap` or `deserializeList` happy to dive into that but thought I ask for opinions before diving in.

Alternatively I have completely missed something obvious and I just need to add some config somewhere which does this all for me but again not obvious and hidden option so this issue would help out other struggling with this in the future. :))

**Comment by zapov** [comment]
Sets should be working out-of-the-box.
You can find it in the example: https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava8/src/main/java/com/dslplatform/maven/Example.java#L21
and various tests.

It would help if you provide a small reproducible, ideally in the form of test case within dsl-json project.

**Comment by adarcanum** [comment]
you are correct - did some testing on my side sets are in fact treated same as lists - seems issue is coming from elsewhere in this case - thanks for quick follow up!!
