### ISSUE TITLE
Question - Is possible to use array format with discriminator in abstract classes

### ISSUE THREAD

**Issue by hvqxyz** [ngs-doo/dsl-json#255]
I have abstract class and 2 implementations of this class. I use discriminator to determine class, but i also want to use array format for this classes. Is any way to do this? 

Currently serialization runs without exception, but in the output the discriminator field isn't separated by comma from the rest of object fields. And the result of serialization cannot be deserialized.

**Comment by zapov** [comment]
It seems there were some bugs there. I've fixed them with latest PR.

**Comment by zapov** [comment]
Fixed in v2
