### ISSUE TITLE
@CompiledJson annotation does not bind byte[] to BinaryConverter in v2.0.0

### ISSUE THREAD

**Issue by j-bahr** [ngs-doo/dsl-json#259]
Previous version so DSL-JSON would correctly map byte[] to BinaryConverter. In the latest 2.0.0 release the annotation processor creates code that won't compile. It tries to create a JsonReader/Writer of type `<byte>`, not `<byte[]>` which fails to compile with the following error:

```
/.../dsl-json/examples/MavenJava/target/generated-sources/annotations/com/dslplatform/maven/_Example$Model_DslJsonConverter.java:163:66
java: unexpected type
  required: reference
  found:    byte
```

You can test this by adding `public byte[] byteArray;` to Model in the `MavenJava` -> `Example.java` file. 

Previous versions of DSL json would create code of the following:
```
private com.dslplatform.json.JsonWriter.WriteObject<byte[]> writer_byteArray; 
```

2.0.0 produces the following:
```
private final com.dslplatform.json.JsonWriter.WriteObject<byte> writer_byteArray;
```

This can probably be worked around by assigning a converter for the type, but would prefer not to as this _should_ work out of the box with the annotation processor.

**Comment by zapov** [comment]
Tnx for the bug report. Fixed in latest commit. Will try to release next week.

**Comment by zapov** [comment]
v2.0.1 released
