### ISSUE TITLE
Deserializing abstract class based on another field value?

### ISSUE THREAD

**Issue by dcrn** [ngs-doo/dsl-json#26]
I have a field that depends on another field's value to define what type it is, something like this:

```
@CompiledJson
public class MyMessage {
    public String valueOne;
    public String valueTwo;
    
    public Thing thing;
    public ThingType type;
}

public enum ThingType { Abc, Xyz }

public interface Thing {}
public class AbcThing implements Thing {}
public class XyzThing implements Thing {}
```

I'm just wondering how the best way to go about this is. I'm not really certain of how I can use JsonConverter for this - because the field is dependent on another field being read first.

**Comment by zapov** [comment]
The best way would be to let DSL-JSON fill in the additional $type used for serialization/deserialization.
As for some manual workarounds... maybe you can have some private field to help you during deserialization?

**Comment by dcrn** [comment]
In my case it would mean filling in the $type field manually in javascript, and I don't really want to do this level of coupling between web client and server.
Can you explain further about the private field during deserialization? I can understand keeping the type information for later, but I'm not sure what to do when the abstract object comes first. Maybe I can define a JsonConverter for the type enum also, then I can fill in the object there if the data came beforehand..

**Comment by zapov** [comment]
Yeah I meant with two converters. Although I think you can get a more cleaner code by having only one field and using alternative names feature (which ought to call your converter two times).
But yes, the problem is what if you object comes first and the type info comes second.
If your input is byte array then you could remember the position and reparse it when you have type info.
If your input is input stream then ideally DSL-JSON would need a skipAndMemoize API which would skip over the object but give you a snapshot of bytes which it skipped over so you can process it later.

**Comment by dcrn** [comment]
Thanks! This seems like a good approach so far. I have to change the abstract object property to be a container though, as I have no reference to the object being deserialized to fill in the value. Do you have any better solution to this?

**Comment by zapov** [comment]
One more "trick" I would try is to use `DslJson<Context>` for storing/passing state. You can access this value in https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/JsonReader.java#L42

**Comment by dcrn** [comment]
Oh great, I'll try that. Thanks.

**Comment by dcrn** [comment]
I was able to do it, but I had a lot of problems.

First of all, because values are assigned to fields after deserialization, I had to make a "proxy" field and ignore the actual field I was assigning to. But this only works for deserialization, as during serialization those fields are ignored. Perhaps a ignore_on_deserialize/ignore_on_serialize option would be useful?

Second, because I didn't want to write a converter class manually for each class (Instead just using the CompiledJson dsl), I had to make a converter which copies the bytes for the entire object from the JsonReader into a new JsonReader object. This is included below:

```
public class DictionaryToJsonReader {
    public static <T> JsonReader<T> read(JsonReader jsonReader) throws IOException {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        bytes.write('{');

        if (jsonReader.last() != 123) {
            throw new IOException("Expected '{' at position " + jsonReader.positionInStream() + ", got '" + jsonReader.last() + "'");
        }

        int size = 1;
        int openBraces = 0;
        boolean escape = false;
        boolean inString = false;
        do {
            if (jsonReader.last() == 34 && !escape) {
                inString = !inString;
            }

            if (jsonReader.last() == 92) {
                escape = !escape;
            } else {
                escape = false;
            }

            if (!inString && jsonReader.last() == 123) {
                openBraces++;
            } else if (!inString && jsonReader.last() == 125) {
                openBraces--;
            }

            if (openBraces == 0) {
                break;
            }

            try {
                bytes.write(jsonReader.read());
                size++;
            } catch (IOException ex) {
                throw new IOException("Expected '}' at position " + jsonReader.positionInStream());
            }
        } while (true);

        JsonReader<T> outReader = new JsonReader<>(bytes.toByteArray(), size, null);

        try {
            outReader.read();
        } catch (Exception ignored) {
        }

        return outReader;
    }
}

```

Third, I was unable to get a reference to the object being deserialized from the converter, so I had to use a reference from the constructor of the main class. I made some helper class to handle all of this, so my class ended up looking like this:
```
class Message {
    private final static Map<Object, Class> typeDeserializeMap = Stream.of(
            new AbstractMap.SimpleEntry<>(PropertiesType.Special, SpecialProperties.class),
            new AbstractMap.SimpleEntry<>(PropertiesType.None, NoneProperties.class),
            new AbstractMap.SimpleEntry<>(PropertiesType.Other, OtherProperties.class)
    ).collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));

    @JsonAttribute(ignore = true)
    public Properties properties;

    @JsonAttribute(ignore = true)
    public PropertiesType propertiesType;

    @JsonAttribute(name = "properties", mandatory = true, converter = SpecifiedTypeDeserializer.ProxyFieldConverter.class)
    public Object __proxy_properties;

    @JsonAttribute(name = "properties_type", mandatory = true, converter = SpecifiedTypeDeserializer.ProxyTypeConverter.class)
    public Object __proxy_properties_type;

    public Message() {
        SpecifiedTypeDeserializer.getLocal().initialize(
                typeDeserializeMap,
                PropertiesType::valueOf,
                (val) -> this.properties = (Properties) val,
                (type) -> this.propertiesType = (PropertiesType) type
        );
    }
}
```

**Comment by zapov** [comment]
Thanks for the report. When I find some time I'll look into how this can be improved.

JsonReader on byte[] input can be improved with the use of skip method, but for stream input something else needs to be done.

If I add an alias for type name so instead of actual type something else can be written out, that would partly help with your use case.

I still think use of custom context would help here, so thats something I'll try when I take a relook at this.

Regards,
Rikard

**Comment by dcrn** [comment]
I'm not sure of how I can use a custom context for this. Do you have some examples?
Cheers for the help by the way. I really like this library so far.

**Comment by zapov** [comment]
I don't currently. I guess I'll have to write something first :)
