### ISSUE TITLE
support for kotlin value classes

### ISSUE THREAD

**Issue by adarcanum** [ngs-doo/dsl-json#264]
in kotlin when using a value class in a data class annotated by `@CompiledJson`, converter fails to be generated

```
@JvmInline
value class MyValue(val value: String)
@CompiledJson
data class MyObject2(val e: MyValue)
```

results in:

```
error: No matching constructors found for 'com.example.MyObject2'. Make sure there is at least one matching constructor available.
```

current workaround involves writing a custom converter for any object being serialised by dsljson that contains an inline value class - ideally would be nice for generator to pick that up

**Comment by zapov** [comment]
If you can make such a test case in Kotlin and replicate such test in Java that would help in understanding whats missing

**Comment by adarcanum** [comment]
@zapov can you point me to an example test so i can see what you are expecting

**Comment by vans239** [comment]
Kotlin value classes can be used with certain hacks

```
  @JsonAttribute(converter = JsonParsing.MyValueConverter::class)
  @set:JvmName("px")
  @get:JvmName("px")
  var value: MyValue = ""
```
where MyValueConverter is 
```
        class RawConverter {
            companion object {
                @JvmStatic
                fun read(reader: JsonReader<*>): String = ...
                @JvmStatic
                fun write(writer: JsonWriter, value: String) = ...
            }
        }
```

**Comment by zapov** [comment]
Kotlin tests can be found in tests-kotlin project.

By replicating it in Java class I mostly mean writing the equivalent class for Kotlin in Java.
You can find those in some generated metadata from Kotlin project.
Here is an example where I added Kotlin class and test + replicated the same in pure Java: https://github.com/ngs-doo/dsl-json/commit/be9f8f17a342b1dcd392f60a8dccbf92c053980e
Sometimes they might be somewhat exotic with strange type signatures :/

**Comment by adarcanum** [comment]
@vans239 much appreciated for the workaround I can confirm that the following prints expected values.

```
@JvmInline
value class MyValue(val value: String)
@CompiledJson
class MyObject3 {
    @set:JvmName("e")
    @get:JvmName("e")
    var e: MyValue? = null
    override fun toString(): String {
        return "MyObject3(e=$e)"
    }
}

fun main() {
    val s = MyObject3().apply {
        e = MyValue("s")
    }
    println(s)
    val bos = ByteArrayOutputStream()
    dslJson.serialize(s, bos)
    val r = bos.toString(Charsets.UTF_8)
    println(r)
    val t = dslJson.deserialize(MyObject3::class.java, r.byteInputStream())
    println(t)
}
```

@zapov thanks for pointing me to test example, I decided to close this issue in the meantime as it is possible to get kotlin value classes to work with dsljson. 

A note for future is that you cannot use kotlin value classes in the constructor of kotlin data classes or kotlin classes or potentially java classes (did not test that) in combination with `@CompiledJson` - it is however possible (but cumbersome) to achieve this with a custom converter for each class that uses a kotlin value class in its constructor.
