### ISSUE TITLE
Re-using reader/writer. Make reset method public

### ISSUE THREAD

**Issue by kozel-aliaksei** [ngs-doo/dsl-json#268]
1. Current `deserialize` has the following structure:

```
	public <TResult> TResult deserialize(...) {
	        ...
		final JsonReader json = localReader.get().process(stream);
		try {
			return deserialize(manifest, json, stream);
		} finally {
			json.reset();
		}
	}
```

I can't reuse `JsonReader` via `ThreadLocal` because it is not available in the `EventLoop` concurrency model that I am using (project Reactor).

2. That is why I am creating new `Reader` and `Writer` per each JSON:
`DSL_JSON.newReader().process(new ByteBufInputStream(source));`

3. I would like to create a pool of `Reader` and `Writer`, and re-use them instead of creating a new buffer per each call. But to do I need to be able to `.reset()` json object before I get back it into the pool. Could you please make `reset` method public? So I can add this to my `releaseHandler` of ObjectPool?

**Comment by kozel-aliaksei** [comment]
Also I didn't manage to re-use `jsonReader` by simply passing new `InputStream` to `.process` method. I just got an
`com.dslplatform.json.JsonReader$EmptyEOFException`

**Comment by zapov** [comment]
It should be sufficient to just use process. If that doesn't work thats a bug to fix. Can you make a PR which reproduces this bug?

`reset` is mostly to get rid of holding a reference to an object. If you need to replicate that (without making reset public) it should be sufficient to do something like `process(empty array)` but that does assume process works as expected.

**Comment by kozel-aliaksei** [comment]
ok, I found an issue. When I used
