### ISSUE TITLE
Downloaded compiler executable is not kept

### ISSUE THREAD

**Issue by dcrn** [ngs-doo/dsl-json#27]
Currently the dsl-platform.com website is down, meaning I cannot download the compiler tool as required. It would be good if the executable is cached in case of server downtime.

**Comment by dcrn** [comment]
I think it would be good to have a mirror for the compiler executable also, on github or some other website.

**Comment by zapov** [comment]
It should be cached in your temp /DSL-Platform folder. There  is some older version on github/revenj

**Comment by dcrn** [comment]
I tried the older version in revenj, but it doesn't seem compatible. 
Is the compiler open source? Can I build it myself?
I'm at work right now waiting for the website to come back online so I can compile my project.

**Comment by zapov** [comment]
This is the latest version: https://github.com/ngs-doo/dsl-json/releases/tag/1.4.2

**Comment by dcrn** [comment]
Thanks so much!!

**Comment by decervelage** [comment]
Is the compiler in Github somewhere?  I see the other components, but not that one.

**Comment by zapov** [comment]
The compiler is not in a public repository. It's free to use, but access to source is currently licensed

**Comment by decervelage** [comment]
Okay.  Thanks.

**Comment by zapov** [comment]
user.home folder will be used as of v1.7.1 instead of temp folder

But I suggest switching to Java8 annotation processor version.
It should have the same performance (maybe even better in some cases)
