### ISSUE TITLE
Is there any support for deserialiazing from already parsed data?

### ISSUE THREAD

**Issue by kaqqao** [ngs-doo/dsl-json#270]
I have a situation where I receive `Map<String, Object>` (where `Object` is either one of the leaf types (Strings and primitives), another `Map`, or a List of any of the previously mentioned) and I have to deserialize it into a POJO. Is there a method in this lib, akin to Jackson's `convertValue(map, Pojo.class)`, that I could use here? I understand my scenario is pretty much unrelated to JSON, but it's adjacent so a few libs expose such a feature and I figured it's worth asking.

**Comment by zapov** [comment]
There is none.

**Comment by kaqqao** [comment]
Bummer, but thanks for responding 👍
