### ISSUE TITLE
Runtime reflection doesn't handle primitive boolean variables correctly

### ISSUE THREAD

**Issue by zzl221000** [ngs-doo/dsl-json#271]
from `com.dslplatform.json.runtime.ObjectAnalyzer#analyzeMethods`

```java
		if (mget.getParameterTypes().length != 0) return false;
		final String setName = mget.getName().startsWith("get") ? "set" + mget.getName().substring(3) : mget.getName();
		final Method mset;
		try {
			mset = manifest.getMethod(setName, mget.getReturnType());
		} catch (NoSuchMethodException ignore) {
			return false;
		}
```

If the method does not start with get, the original method name is used. This is compatible with chained calls, but non-chained calls to getter methods of primitive boolean types start with is.

**Comment by zapov** [comment]
Eh, yeah. A lot of stuff is missing in reflection-only serialization.

Do you need it, or just noticed?

**Comment by zzl221000** [comment]
@zapov 
I require it; some of the POJOs are part of third-party libraries, and I'm unable to add the CompiledJson annotation.

**Comment by zapov** [comment]
If you put a CompiledJson on your class which has external classes as property, dsl-json will still create converters for it due to transitive dependency and analysis.
So it should not matter if its in third party library, as long as you can import it in your project and create such relationship.

**Comment by zzl221000** [comment]
> If you put a CompiledJson on your class which has external classes as property, dsl-json will still create converters for it due to transitive dependency and analysis. So it should not matter if its in third party library, as long as you can import it in your project and create such relationship.

Thanks for the suggestion. Unfortunately, my POJO are generated as class files by a third-party library using an annotation processor, and extending these classes is not a straightforward task.

I shadowed the original ObjectAnalyzer class and implemented some basic fixes.
