### ISSUE TITLE
Techempower benchmark using dsl-json

### ISSUE THREAD

**Issue by awmcc90** [ngs-doo/dsl-json#276]
I submitted a [PR](https://github.com/TechEmpower/FrameworkBenchmarks/pull/9172) to TechEmpower benchmarks which makes use of dsl-json for serialization alongside Vert.x web framework. I wanted to reach out and see if it would be possible to get this reviewed by the dsl-json team to ensure the implementation is both correct and optimal.

Let me know if you have any questions or issues with this too. Thanks!

**Comment by zapov** [comment]
I dont have time to do more than superficially look over the code.
The only thing I find suspicious is use of this string caching.
This is something you should benchmark as there are use cases when this helps, but there are also use cases when its better to leave it to Java.
Anyway, I'm gonna assume you did bench it and thats why you left it so it seems fine.

**Comment by awmcc90** [comment]
Thanks for the reply.  I did benchmark both and it's sort of a mixed bag. It looks like _generally_ including the string value cache is more efficient for most test cases. I'm attaching the results of the two tests for you to take a look if you're interested. The `totalRequests` field for each test/concurrency level combination is what matters.

I'm going to leave it in for now and do some more thorough testing on it later. But given you've looked at this I'll go ahead and close this. Thanks again and let me know if you'd like me to change anything in the future.

[with_string_value_cache.json](https://github.com/user-attachments/files/16484381/with_string_value_cache.json)
[without_string_value_cache.json](https://github.com/user-attachments/files/16484382/without_string_value_cache.json)
