### ISSUE TITLE
JsonAttribute ignored on interface method implementations

### ISSUE THREAD

**Issue by dcrn** [ngs-doo/dsl-json#29]
There seems to be a new issue with JsonAttribute in the latest version.

```
public interface TestInt {
    long getValue();
    void setValue(long v);
}
```

```
@CompiledJson
public class TestObject implements TestInt {
    private long value;

    @Override
    @JsonAttribute(name = "my_data")
    public long getValue() {
        return value;
    }

    @Override
    @JsonAttribute(name = "my_data")
    public void setValue(long v) {
        this.value = v;
    }
}
```

Output is: `{"value":123}`, but should be `{"my_data":123}`

**Comment by dcrn** [comment]
Looks like the getBeanProperties processor function will only return the highest level method, which is the interface's in this case. The getter method is overwritten by the superclass method with the same name:

https://github.com/ngs-doo/dsl-json/blob/master/processor/src/main/java/com/dslplatform/json/CompiledJsonProcessor.java#L1170

Maybe the low level method handle should be kept if a JsonAttribute has been defined on it?

**Comment by zapov** [comment]
Thanks for the bug report and the fix.
I've merged it in https://github.com/ngs-doo/dsl-json/commit/000e32ceb3204186cf707c50099f7479cc8e9411

Can you build your own processor, or do you want me to release it?

**Comment by dcrn** [comment]
Looks good! Thanks 👍 
If you have time a release would be great.
