### ISSUE TITLE
JsonStreamReader.getLastName returns incorrect data sometimes

### ISSUE THREAD

**Issue by dcrn** [ngs-doo/dsl-json#30]
From what I can gather, it seems like this happens after JsonStreamReader reads from the stream into the buffer - in-between the name and value of the json property. The buffer doesn't contain the name anymore, so it can't be extracted properly (specifically [here](https://github.com/ngs-doo/dsl-json/blob/2fdc8c425833ee57f3e047ece9c451daf93d7528/library/src/main/java/com/dslplatform/json/JsonReader.java#L564-L566)).

**Comment by zapov** [comment]
I'll see what can be done about it. It doesn't seem trivial to fix :(

**Comment by dcrn** [comment]
I thought I could get around this by increasing my buffer size, but I noticed that JsonStreamReader.readFully was being called twice even though my buffer was big enough for the entire stream.
[Here](https://github.com/ngs-doo/dsl-json/blob/2fdc8c425833ee57f3e047ece9c451daf93d7528/library/src/main/java/com/dslplatform/json/JsonStreamReader.java#L47), the readLimit is set lower than the length (I presume to prevent the same issue here), but I don't think there should be a readLimit if the length is less than the buffer size, right?

**Comment by zapov** [comment]
Read limit is set to half the buffer size to prevent some issues about rewriting the buffer. The second read could probably be avoided, but I don't think that will help in all cases.
It seems that when readFully is invoked it should cope with name positions which it currently ignores, eg. it should reset buffer to name start, not to 0

**Comment by dcrn** [comment]
> Read limit is set to half the buffer size to prevent some issues about rewriting the buffer. 

My buffer length is 16384, but readLimit is 169; half of the length of the streamed data. It looks like there will be multiple reads regardless of buffer length.

**Comment by zapov** [comment]
Yeah. Its due to https://github.com/ngs-doo/dsl-json/blob/2fdc8c425833ee57f3e047ece9c451daf93d7528/library/src/main/java/com/dslplatform/json/JsonStreamReader.java#L82
This should be fixed.
But multiple reads as still required... since it reads until 0 bytes are read

**Comment by dcrn** [comment]
>Yeah. Its due to https://github.com/ngs-doo/dsl-json/blob/2fdc8c425833ee57f3e047ece9c451daf93d7528/library/src/main/java/com/dslplatform/json/JsonStreamReader.java#L82
This should be fixed.

I believe the same issue is [here](https://github.com/ngs-doo/dsl-json/blob/2fdc8c425833ee57f3e047ece9c451daf93d7528/library/src/main/java/com/dslplatform/json/JsonStreamReader.java#L47) also (JsonStreamReader constructor).

**Comment by zapov** [comment]
Tnx for the bug report. I've released a new version. Issue should be fixed now

**Comment by dcrn** [comment]
Seems to be working so far! Thanks!
