### ISSUE TITLE
Cannot serialize nested collections

### ISSUE THREAD

**Issue by dcrn** [ngs-doo/dsl-json#31]
I just ran into an issue while handling some map data from another library - nested lists can't be serialized.

My test code:
```
DslJson dsl = new DslJson();
dsl.serializeMap(
        Collections.singletonMap("x",
                Collections.singletonList(Collections.singletonList("Hello"))
        ),
        dsl.newWriter()
);
```

I think the issue is around [here](https://github.com/ngs-doo/dsl-json/blob/028a1ea40371404a918f652dd1323b6bf2a6daa4/library/src/main/java/com/dslplatform/json/DslJson.java#L2086-L2124)

**Comment by zapov** [comment]
As a temporary workaround you can register your own generic collection handler:

    class CollectionWriter implements JsonWriter.WriteObject<Collection> {
      private final DslJson dslJson;
  
      public CollectionWriter(DslJson dslJson) {
        this.dslJson = dslJson;
      }
  
      @Override
      public void write(JsonWriter writer, Collection value) {
        writer.writeByte((byte)'[');
        boolean isFirst = true;
        for(Object it : value) {
          if (isFirst) isFirst = false;
          else writer.writeByte((byte)',');
          if (it == null) writer.writeNull();
          else dslJson.serialize(writer, it.getClass(), it);
        }
        writer.writeByte((byte)']');
      }
    }
  
    @Test
    public void testSerialization() throws IOException {
      DslJson dsl = new DslJson<Object>();
      dsl.registerWriter(Collection.class, new CollectionWriter(dsl));
      JsonWriter jw = dsl.newWriter();
      dsl.serializeMap(
          Collections.singletonMap("x",
              Collections.singletonList(Collections.singletonList("Hello"))
          ),
          jw
      );
      Assert.assertEquals("{\"x\":[[\"Hello\"]]}", jw.toString());
    }

**Comment by dcrn** [comment]
Ah great, I didn't think of that. Thanks!

**Comment by zapov** [comment]
So I looked at this some more... and due to way that dsl-json was designed with upfront schema in mind this doesnt work out of the box.
I do plan on removing the fallback functionality from the library... and then this should work as expected.
This can be left as reminder to remove the fallback.
