### ISSUE TITLE
Double optimizations

### ISSUE THREAD

**Issue by zapov** [ngs-doo/dsl-json#37]
Reduce how often Double.parseDouble must be called

**Comment by zapov** [comment]
Fixed via precision setting.
It turns out that previous deserialization method is not fully correct (when dealing with more than 15 digits). Neither is the new default one (although it's more correct).
For full precision HIGH should be enough.
For lower GC LOW can be used.

**Comment by xttam** [comment]
I'm sorry I'm commenting on a closed thread but what is the correct way now? I don't see any pull being merged here, what is this referring to? Thanks.

**Comment by xttam** [comment]
Don't know how that flag affects parsing, but I debugged the code and `NumberConverter.deserializeDouble(reader)` was calling `Double.parseDouble()` internally, with no precision check whatsoever.

**Comment by zapov** [comment]
The code for parsing double is trying to figure out if it can skip over allocating the string and calling Java Double parse. If it can't most of the time, then yes, it looks like just an overhead.
