### ISSUE TITLE
WOW,ERROR

### ISSUE THREAD

**Issue by shaogaige** [ngs-doo/dsl-json#38]
DslJson<Object> dslJson = new DslJson<>();
JsonWriter writer2 = dslJson.newWriter();
List<Object> o = new ArrayList<Object>();
		o.add("Hello Word!");
		o.add(1);
		o.add(false);
		
dslJson.serialize(writer2, o);
System.out.println(writer2.toString());

how could this happen ?

**Comment by zapov** [comment]
You mean `java.lang.ClassCastException: java.lang.String cannot be cast to com.dslplatform.json.JsonObject` ?

I guess Java thinks

    public <T extends JsonObject> void serialize(JsonWriter writer, List<T> list) {

is better fit then

    public final void serialize(JsonWriter writer, Object value) throws IOException {

While you can workaround it via

    dslJson.serialize(writer, (Object) o);

or 

    List<Object> o = new ArrayList();

it's not really much of an experience :(

I guess I might wanna change the API not to confuse Java :(

**Comment by shaogaige** [comment]
to be honest, i met a problem: how to add different type(String,int,double,boolean) value into a json-array,just like a json in js.
i have heard dsl-json is the most fast lib to do with json, did you have think about this situation ?








At 2017-09-07 12:25:59, "zapov" <notifications@github.com> wrote:


You mean java.lang.ClassCastException: java.lang.String cannot be cast to com.dslplatform.json.JsonObject ?

I guess Java thinks

public <T extends JsonObject> void serialize(JsonWriter writer, List<T> list) {


is better fit then

public final void serialize(JsonWriter writer, Object value) throws IOException {


While you can workaround it via

dslJson.serialize(writer, (Object) o);


or

List<Object> o = new ArrayList();


it's not really much of an experience :(

I guess I might wanna change the API not to confuse Java :(

**Comment by zapov** [comment]
Well, both of the workarounds I suggested will work.
Also if you are targeting an output stream use that API directly

    dslJson.serialize(o, outputStream);

If you wish to use a writer I suggest using

    List<Object> o = new ArrayList();

instead of 

    List o = new ArrayList();

**Comment by shaogaige** [comment]
ok, i will have a try.







在 2017-09-07 17:51:51，"zapov" <notifications@github.com> 写道：


Well, both of the workarounds I suggested will work.
Also if you are targeting an output stream use that API directly

dslJson.serialize(o, outputStream);


If you wish to use a writer I suggest using

List<Object> o = new ArrayList();


instead of

List o = new ArrayList();

**Comment by zapov** [comment]
Marked problematic APIs as deprecated
