### ISSUE TITLE
Several long strings with many ASCII letters following a special character cannot be parsed

### ISSUE THREAD

**Issue by raeger** [ngs-doo/dsl-json#40]
JsonReader.parseString() contains a bug related to the variable _tmpLen, which is at first used to keep track of how many bytes are still ahead in the buffer, and later to reflect the size of the temporary buffer. But it isnt't set to the size of the temporary buffer when it changes its role, so whenever a backslash or UTF-8 multibyte character was encountered, the temporary buffer will often unnecessarily double its size,  which will soon lead to OutOfMemoryError.

		if (i == _tmp.length) {
			_tmp = chars = Arrays.copyOf(chars, chars.length * 2);
		}
		_tmpLen = _tmp.length; // This line needs to be inserted!
		currentIndex = ci;
		int soFar = --currentIndex - startIndex;

**Comment by zapov** [comment]
Tnx. Do you want to make a PR for that?

Also on two places that check

    if (newSize > maxStringSize) throw new IOException("Unable to process input JSON. Maximum string size limit exceeded: " + maxStringSize);

Is missing :(

**Comment by raeger** [comment]
Sorry, I don't use GIT much, that's why I reported the bug this way.

**Comment by zapov** [comment]
Np. Fixed in v1.5.2. Should be up on Maven soon
