### ISSUE TITLE
string buffer limit exceeded error

### ISSUE THREAD

**Issue by SmileZero** [ngs-doo/dsl-json#47]
I tried the new version 1.7.2. The problem about json with emoji has gone. 

However, after handling some JSON strings, it continued raising the following error even if the JSON is a very short string.
```
Unable to process input JSON. Maximum string buffer limit exceeded: 134217728
```

I print the json when it raise error and it is as simple as `{"458165560803868672":{"1":7722,"2":"RT @SivuNgcaba: \"Things we buy to cover up what's inside, coz they made us hate ourselves and love their wealth.\""}}`

I increased the string buffer limitation to 1GB, the whole system will raise heap size is over even if I set the -Xmx=3000m.

Do you have any clue what happened?

I tried 1.7.1 and it is the same.

**Comment by zapov** [comment]
So many bugs ;(

Fixed it just earlier on: https://github.com/ngs-doo/dsl-json/commit/e07b094555601c19ecb8a2eb02e8852018c4ddbe

**Comment by zapov** [comment]
Are you sure you've deployed the latest build?
Please double check that (eg, build it with different version).

**Comment by SmileZero** [comment]
Let me delete the jar file and try again. Maybe I didn't successfully build it.

**Comment by SmileZero** [comment]
It works!!! Thank you so much.
