### ISSUE TITLE
Treating U+FFFE and U+FFFF as invalid in Unicode 16-bit strings is a legacy from the previous millenium

### ISSUE THREAD

**Issue by plokhotnyuk** [ngs-doo/dsl-json#51]
https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/JsonWriter.java#L359

**Comment by zapov** [comment]
Yes, it makes sense to include those two chars in comparison.

Do you want to make a PR for that?
