### ISSUE TITLE
Using "Boolean" attributes result in compile errors in generated code.

### ISSUE THREAD

**Issue by phildebrand** [ngs-doo/dsl-json#53]
I have some "Boolean" attributes in my model class. The generated code contains multiple references to "com.dslplatform.BoolConverter" but it should be referencing to "com.dslplatform.**json**.BoolConverter".

**Comment by zapov** [comment]
Thanks for the bugreport. 
As a temporary workaround until next version is out you can redirect builtin converter via custom converter, eg:

    @CompiledJson
    public static class All {
        @JsonAttribute(converter = Bools.class)
        public Boolean b;
    }

    public abstract static class Bools {
        public static final JsonReader.ReadObject<Boolean> JSON_READER = BoolConverter.NULLABLE_READER;
        public static final JsonWriter.WriteObject<Boolean> JSON_WRITER = BoolConverter.WRITER;
    }

**Comment by zapov** [comment]
Fixed in v1.7.5
