### ISSUE TITLE
Test packages / folder structure (name) is not standard-compliant

### ISSUE THREAD

**Issue by instant-hrvoje** [ngs-doo/dsl-json#6]
The folder structure for test classes is not sub-folder like - currently it is single folder named 'com.dslplatform.json' instead of standard-correct sub-folder structure (com/dslplatform/json), which causes problems with certain IDEs.

**Comment by zapov** [comment]
Yeah, thats IDEA acting smart... Feel free to fix it if you wish ;)

**Comment by zapov** [comment]
Fixed.
