### ISSUE TITLE
CompiledJsonProcessor  error

### ISSUE THREAD

**Issue by LenaYan** [ngs-doo/dsl-json#7]
Hi，i got an error while  compiling code,but i don't know where it come from.

`Warning:Supported source version 'RELEASE_6' from annotation processor 'com.dslplatform.json.CompiledJsonProcessor' less than -source '1.8'`

**Comment by zapov** [comment]
Yeah, that's a standard java source code version warning. Nothing serious. You can ignore it.

I did not looked into if that can be fixed somehow, but not really a priority.

**Comment by LenaYan** [comment]
@zapov  tks a lot ,dsl-json is a great job.
but I don't understand why using mono.......

**Comment by zapov** [comment]
Well, JSON is just a tiny part of the DSL Platform compiler. I guess more of a showcase for people confusing it with an ORMs.
And that's written in C# for historical reasons (and C# is a fine language).
Mono might not be something you wish to run your production servers on, but I don't see real issues with using it as a development utility.

**Comment by zapov** [comment]
Fixed.

**Comment by bluef** [comment]
It would be much better if no mono dependency is required

**Comment by zapov** [comment]
Well, it's only compile time dependency.
And it should work out of the box if you do something along the lines of sudo apt-get install mono-complete or install Mono from http://www.mono-project.com/download/#download-mac

I mean, it's not like I like Mono or something...
But if you are having problems with the setup while trying to configure dsl-json I'd like to hear about it and see if I can fix it somehow.

**Comment by bluef** [comment]
right, i mean there would be some work to have all the developers in our team to install mono for dsl-json... I have no problem compile my code with dsl-json. You've done great work, but the dependency of mono/C# would be some problem for ppl to try out your library. Just my thoughts. :)

**Comment by zapov** [comment]
Well, yeah. I know people would prefer not to have Mono as a dependency :(
But there is not much I can do about that.

**Comment by zapov** [comment]
Tnx @jamespedwards42 
I should probably put a link in README to such a docker image.
I have not put one yet, since I don't use it in such a way... so I'm not very keen on supporting it :/

**Comment by jamespedwards42** [comment]
@zapov , Either way, no biggie, just thought I would share.  If you do have a build in mind that you would like serve as a Docker example, I would be happy to whip up an example for your README.  Also, just want to say thanks for the library, it so nice to finally be able to settle on a performant JSON library.

**Comment by zapov** [comment]
@jamespedwards42 I don't have anything specific in mind. 
But I'm a Docker noob, so if you want to whip something up... great; I'll take a look at it for sure.
If example/setup makes sense to me, I'll add it along the other examples.
