### ISSUE TITLE
Release v1.8.0

### ISSUE THREAD

**Issue by zapov** [ngs-doo/dsl-json#73]
Features and bugfixes:

 * Improved older Android support
 * Multiple level hierarchy
 * Convention based configuration alongside META-INF services
 * Package private classes
 * Improved class loader support
 * Improved error reporting
 * Removing non-inlined code generator
 * Multi-project support improvements
 * Custom META-INF configuration name
 * Gradle incremental annotation processor support
 * CompiledJson on factory methods (instead of ctors)

**Comment by zapov** [comment]
@varahash I plan on releasing new version these days... do you have anything else you are interested in adding to v1.8.0?

**Comment by varahash** [comment]
I would like to add #68, it almost done. 
Also #69 can be added, but there is some source bracking changes, e.g if We change signature `DslJson` to `DslJson<?>` in interfaces, then everyone who implement such interfaces have to make this change too. Is this allowed change for 1.8.0 or it requires 2.0.0?

**Comment by zapov** [comment]
Ok, I'll wait for #68 then.
Hm, for #69 I'd rather then add suppress annotation then for now. We can revisit it later. Is there some other benefit other than stopping compiler from complaining?

**Comment by varahash** [comment]
If this is unacceptable change for this release, then let's leave it as is. Suppress warning is just workaround, I prefer to fix it properly. Actually, the proper fix allow user do not put suppress warning annotation in their code base.
In that case I will provide fix only for option №3 of #69

**Comment by zapov** [comment]
Maybe it's acceptable. I would need to see a list of APIs which would break. If they are not something commonly used it might be ok to change it.

**Comment by zapov** [comment]
v1.8.0 is released. :tada: 
Well done @varahash
