### ISSUE TITLE
CompiledJson in combination with JsonObject doesn't work

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#78]
DslJson unable deserialize/serialize following case:

```
@CompiledJson
public static class Model {
	public JsonObjectReference jsonObject;
}

public static class JsonObjectReference implements JsonObject {
    public void serialize(JsonWriter writer, boolean minimal) {
        ...
    }

    public static final JsonReader.ReadJsonObject<JsonObjectReference> JSON_READER = ...
}
```

You can find example in android project https://github.com/ngs-doo/dsl-json/blob/master/examples/MavenJava6/src/main/java/com/dslplatform/maven/Example.java#L12-L30

The root cause is that DslJson unable find reader/writer for JsonObject

**Comment by zapov** [comment]
Yeah, it seems it was like that on Java8 version always.
I'll look into fixing it

**Comment by zapov** [comment]
Should be fixed on master now
