### ISSUE TITLE
apt fails at processing fields starting with _

### ISSUE THREAD

**Issue by fabienrenaud** [ngs-doo/dsl-json#8]
100% repro with the 2 simple following files:

**build.gradle**

    plugins {
        id "net.ltgt.apt" version "0.6"
    }

    apply plugin: 'java'

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    repositories {
        mavenCentral()
    }

    sourceSets {
      main {
        java {
          srcDir 'src'
        }
      }
    }

    dependencies {
        // DSL-json
        compile group: 'com.dslplatform', name: 'dsl-json', version: '1.1.1'
        apt group: 'com.dslplatform', name: 'dsl-json-processor', version: '1.2'

        // Test
        testCompile group: 'junit', name: 'junit', version: '4.12'
    }

    test {
        testLogging {
            exceptionFormat = 'full'
            // showStandardStreams = true
        }
    }

in src/thepack/TheObj.java

    package thepack;

    import com.dslplatform.json.CompiledJson;

    @CompiledJson
    public class TheObj {

      public String _id;

    }

then: `gradle build`

    :compileJava
    ~/dsljsonbug/build/generated/source/apt/main/dsl_json/json/ExternalSerialization.java:44: error: cannot find symbol
                if (self.id != null) {
                        ^
      symbol:   variable id
      location: variable self of type TheObj
    ~/dsljsonbug/build/generated/source/apt/main/dsl_json/json/ExternalSerialization.java:47: error: cannot find symbol
                    sw.writeString(self.id);
                                       ^
      symbol:   variable id
      location: variable self of type TheObj
    ~/dsljsonbug/build/generated/source/apt/main/dsl_json/json/ExternalSerialization.java:55: error: cannot find symbol
                if (self.id != null) {
                        ^
      symbol:   variable id
      location: variable self of type TheObj
    ~/dsljsonbug/build/generated/source/apt/main/dsl_json/json/ExternalSerialization.java:57: error: cannot find symbol
                    sw.writeString(self.id);
                                       ^
      symbol:   variable id
      location: variable self of type TheObj
    ~/dsljsonbug/build/generated/source/apt/main/dsl_json/json/ExternalSerialization.java:138: error: cannot find symbol
            instance.id = _id_;
                    ^
      symbol:   variable id
      location: variable instance of type TheObj
    5 errors
    :compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
    > Compilation failed; see the compiler error output for details.

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 6.618 secs

Versions:

    > java -version
    java version "1.8.0_45"
    Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

    > mono --version
    Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:48 PDT 2016)
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
      TLS:           normal
      SIGSEGV:       altstack
      Notification:  kqueue
      Architecture:  amd64
      Disabled:      none
      Misc:          softdebug
      LLVM:          supported, not enabled.
      GC:            sgen

**Comment by zapov** [comment]
Ah, yes... Undocumented restriction ;(

Is this something you need or you just noticed it? I've been pushing properties starting with _ under the rug for a long time.

**Comment by zapov** [comment]
btw. if you need it in just JSON you can use attribute name eg: https://github.com/ngs-doo/dsl-json/blob/master/examples/Maven/src/main/java/com/dslplatform/maven/Example.java#L16

But let's keep this open. I should really fix that annoying restriction.

**Comment by fabienrenaud** [comment]
Sadly, I have other constraints on that class and I can not rename that field. :(
Please support the _ and let me know when it's released :)

**Comment by zapov** [comment]
It should be fixed now.
Let me know if it's working for you.

**Comment by fabienrenaud** [comment]
Thank you. It is fixed indeed.

**Comment by zapov** [comment]
Great ;)

btw. couple of suggestions for your bench

ThreadLocal initialization: https://github.com/TechEmpower/FrameworkBenchmarks/blob/bfef7708639b4a5cca29cc4a7e327dc643071264/frameworks/Java/servlet-dsl/src/main/java/dsl/Utils.java#L7
Reset before use: https://github.com/TechEmpower/FrameworkBenchmarks/blob/bfef7708639b4a5cca29cc4a7e327dc643071264/frameworks/Java/servlet-dsl/src/main/java/dsl/Utils.java#L16
Writer to string (if you really need to): https://github.com/ngs-doo/dsl-json/blob/master/library/src/main/java/com/dslplatform/json/JsonWriter.java#L326
Avoid strings. Copy result to output stream instead of allocating strings. On JsonWriter you have `toStream(OutputStream)` method.
Reuse ByteArrayOuputStreams across loops. Otherwise you will bench allocation instead of JSON. You can reuse by calling `reset()` before use.

Looking forward to the result :)

**Comment by fabienrenaud** [comment]
I actually already had the ThreadLocal optimization for dsl-json since it is documented on your README :) but your comment made me realize I should just do that for all the benchmarks where it makes sense.

I reran all the benchmarks with dsljson and a few extra libs and the least I can say is that you killed it: https://github.com/fabienrenaud/java-json-benchmark 

Congratulations!
