### ISSUE TITLE
Support custom names for enum cases

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#83]
Here is few possible solutions:

1) Allow JsonAttribute annotation on enum
```
enum MyEnum {
    @JsonAttribute(name = "abc")
    SOME_VALUE
}
```

2) Create new annotation and annotate each enum case, e.g JsonValue
```
enum MyEnum {
    @JsonValue(name = "abc")
    SOME_VALUE
}
```

3) Create new annotation and annotate getter which can provide name (like Jackson)
```
enum MyEnum {
    SOME_VALUE("abc")

    private final String value;
    MyEnum(String value) {
         this.value = value;
    }

    @JsonValue
    public getValue() {
        return value;
    }
}
```

**Comment by zapov** [comment]
I'd prefer that annotation can have multiple purposes, so it can support other useful features, eg something like:

    `@JsonEnumAttribute(value = "abc", alternativeValues = { "def", "ghi" })`

even with currently only `value` being implemented.
On the other hand people often use enums as integers in which case the last option looks kind off good.
I guess it boils down to how much do we want to ease up on the common scenario (and what the common scenario actually is).

Currently leaning on the third option which support alternative property types and creates optimized implementation which enumerates all possible values (and takes into account CompiledJson settings for enum.
