### ISSUE TITLE
Add support for serializing java.lang.Object fields in classes annotated with @CompiledJson

### ISSUE THREAD

**Issue by varahash** [ngs-doo/dsl-json#85]
Currently if class contains field of Object type, then DslJson unable to find writer for such field. e.g:

```
@CompiledJson
class Model {
    public String key;
    public Object value;
}
```

**Comment by zapov** [comment]
But this should work as long as you enable runtime conversion? In that case value is probed at runtime for it's type.

**Comment by varahash** [comment]
It does not work, because code generated in converters looks like this:
`this.value_writer = json.tryFindWriter(new TypeReference<Object>{}.type)`

**Comment by zapov** [comment]
Ah right. I see. It's the same issue as finishing up the generic serialization

**Comment by varahash** [comment]
We can fix code generator or create 'UNKNONW_WRITE' similar to already exists 'UNKNOWN_READER'.

**Comment by zapov** [comment]
Hopefully I'll find some time by the week end to go though some related stuff.
I saw that even enums don't generate code as expected - when you use JsonConverter. They go through tryFindWriter instead of going to the target directly.

And code gen needs to handle this unknown stuff in a similar manner as the runtime probing does. If you wish to explore it go ahead. Although it would be nice to first improve on the enum implementation - to use OptimizedConverter for type probing instead of checking for String and int directly.

**Comment by zapov** [comment]
I've added the 'UNKNONW_WRITER' so it works now if you enable it.
The setup should be simplified... it's somewhat cryptic now.

Also, ideally I would prefer that Object types throw compiler errors by default, but that looks kind of nazi (you would need to enable `<Adsljson.unknown>WARNING</Adsljson.unknown>` before it compiles).
@varahash whats your stance on that?

**Comment by varahash** [comment]
I think we should not treat Object type as unknown.

Situation 1:
User created POJO with field of type Object, so he expect that library will try to serialize that field at runtime if it can.

Situation 2:
User created POJO with field of type 'com.example.MyDate', this is actually unknown type, because we already known that we have not converter for such type. Here user expects that annotation processor fails with error that this type is unknown.

So if we will treat 'Object' type as unknown and user will set 'Adsljson.unknown' flag to warning, then he missed error described in second situation.

**Comment by varahash** [comment]
For actually unknown types throw error by default.
For Object types print warning by default.

**Comment by zapov** [comment]
I think a good compromise would be to treat such properties as problematic as long as they don't have `@JsonAnnotation`
That way you can mark them as `known` and move on

Can you add some test for those scenarios so they work in an acceptable way?
I would prefer that there is an option to treat stuff which require runtime as error (although it doesn't need to be by default)

**Comment by varahash** [comment]
Do you propose annotate property of any unknown type or Object only?

**Comment by varahash** [comment]
Here is problem. If user use @JsonAnnotation to provide property name, then he will unintentionally mark all properties as 'known'.

**Comment by varahash** [comment]
That make sense. What about following properties?
```
@CompiledJson
static class UnknownModel {
  public List<Object> value;
  public MyGeneric<Object> value;
}
```

**Comment by zapov** [comment]
We certainly need the common converter for list and maps as common types.

I guess what we want is to whitelist Object as a known type, which looks like it can be handled by:
 1) either registering Object as known type
 2) declaring JsonConverter for Object type

This looks good to me (although it doesn't work yet...)

    @JsonConverter(target = Object.class)
    public static class ObjectRuntimeConverter { ...}

This marks Object as a known type and it will no longer be considered unknown.

**Comment by varahash** [comment]
But can we provide default ObjectRuntimeConverter and enable it with annotation processor flag (by default off), to avoid declaring this ObjectRuntimeConverter each time in new project/module?

**Comment by zapov** [comment]
Such converter would fall under the common converters I mentioned, although I wouldn't add the JsonConverter annotation to it.
It seems better to have something like ObjectConfiguration which would register reader and writer for Object.class - since it would have the same effect.
So the only question becomes how to enable such configuration for the annotation processor. I guess flag just for that seems kind of fine... Although there might be another better solution... (separate project just for that doesnt look like a better solution... :/ )

**Comment by zapov** [comment]
There are now some builtin converters:
https://github.com/ngs-doo/dsl-json/blob/master/java8/src/main/java/com/dslplatform/json/runtime/CollectionAnalyzer.java#L13
https://github.com/ngs-doo/dsl-json/blob/master/java8/src/main/java/com/dslplatform/json/runtime/ObjectAnalyzer.java#L14

JsonConverter now also works:

    @JsonConverter(target = Object.class)
    public static class ObjectRuntimeConverter { ... }

It would be nice to remove it from Map also, but I don't plan on doing it for this release.

Does that cover main use cases?

**Comment by varahash** [comment]
Yeah, I think it is enough for main use case. Thanks!
