### ISSUE TITLE
incorrect error message on field with unsupported type

### ISSUE THREAD

**Issue by dmjef** [ngs-doo/dsl-json#9]
The error message states:
`error: Specified type not supported. If you wish to ignore this property, use one of the supported JsonIgnore annotations (such as Jackson @JsonIgnore or DSL-JSON @JsonAnnotation(ignore = true) on field`
but the DSL-JSON annotation type is JsonAttribute, not JsonAnnotation.

**Comment by zapov** [comment]
Tnx.
