### ISSUE TITLE
Missing register Object writer when serialize generic object

### ISSUE THREAD

**Issue by foxpify** [ngs-doo/dsl-json#92]
I have some models:
**Subscriber**:

`@CompiledJson
public class Subscriber {
    private Long id;
    private Long shopId;
    private UUID campaignId;
    private String fullName;
    private String email;
    private OffsetDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getShopId() {
        return shopId;
    }

    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    public UUID getCampaignId() {
        return campaignId;
    }

    public void setCampaignId(UUID campaignId) {
        this.campaignId = campaignId;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
`

**Page**:

`import java.util.List;

public class Page<E> {
   private int currentPage;
   private int pageSize;
   private int totalPage;
   private int totalCount;
   private List<E> content;

   @CompiledJson
   Page(int currentPage, int pageSize, int totalPage, int totalCount, List<E> content) {
      this.currentPage = currentPage;
      this.pageSize = pageSize;
      this.totalPage = totalPage;
      this.totalCount = totalCount;
      this.content = content;
   }

   public Page(PageRequest pageRequest, int totalCount, List<E> content) {
      this(pageRequest.getIndex(), pageRequest.getSize(), totalCount,content);
   }

   public Page(int currentPage, int pageSize, int totalCount, List<E> content) {
      this.currentPage = currentPage;
      this.pageSize = pageSize;
      this.totalPage = (totalCount + (pageSize - 1)) / pageSize;
      this.totalCount = totalCount;
      this.content = content;
   }

   public int getCurrentPage() {
      return currentPage;
   }

   public int getPageSize() {
      return pageSize;
   }

   public int getTotalPage() {
      return totalPage;
   }

   public int getTotalCount() {
      return totalCount;
   }

   public List<E> getContent() {
      return content;
   }
}
`
when I try serialize object page of Subscriber:

`DslJson.Settings settings = Settings.withRuntime().includeServiceLoader();
        DslJson<Object> json = new DslJson<Object>(settings);
        PageRequest pageRequest = new PageRequest(1, 20);
        List<Subscriber> content = new ArrayList<>();
        content.add(new Subscriber());
        Page<Subscriber> products = new Page<>(pageRequest, 0, content);

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        json.serialize(products, outputStream);
        System.out.println(new String(outputStream.toByteArray(), StandardCharsets.UTF_8));`

I got error:

`java.io.IOException: Unable to serialize provided object. Failed to find serializer for: class com.foxpify.vertxorm.util.Page

	at com.dslplatform.json.DslJson.serialize(DslJson.java:2784)`
This cause due when dsl-json try to resolve ParameterizedType but fallback to Object.class 
`if (manifest instanceof java.lang.reflect.ParameterizedType) {
				java.lang.reflect.ParameterizedType pt = (java.lang.reflect.ParameterizedType) manifest;
				java.lang.Class<?> rawClass = (java.lang.Class<?>) pt.getRawType();
				if (rawClass.isAssignableFrom(com.foxpify.vertxorm.util.Page.class)) {
					return new ObjectFormatConverter(__dsljson, pt.getActualTypeArguments());
				}
			} else if (com.foxpify.vertxorm.util.Page.class.equals(manifest)) {
				java.lang.reflect.Type[] unknownArgs = new java.lang.reflect.Type[1];
				java.util.Arrays.fill(unknownArgs, Object.class);
				if (__dsljson.tryFindReader(Object.class) != null && __dsljson.tryFindWriter(Object.class) != null) {
					return new ObjectFormatConverter(__dsljson, unknownArgs);
				}
			}`

__dsljson.tryFindReader(Object.class) return not null but __dsljson.tryFindWriter(Object.class) != null)  this cause error.
I have to manual register writer: json.registerWriter(Object.class, ObjectAnalyzer.Runtime.JSON_WRITER); then it work
Env: java 11
OS: MacOS

**Comment by zapov** [comment]
I think we'll enable object writer by default when using `withRuntime`.
For now you should be able to work around it by registering it manually during setup: https://github.com/ngs-doo/dsl-json/blob/master/tests-java8/src/test/java/com/dslplatform/json/GenericTest.java#L95

**Comment by zapov** [comment]
v1.8.3 now enables unknown writer by default
