### ISSUE TITLE
Polymorphic Deserialization

### ISSUE THREAD

**Issue by ma1uta** [ngs-doo/dsl-json#96]
Is there way to enable polymorphic deserialization?

For example, I have 

```
abstract class A {
  public abstract String getType();

  public int i;
}

class B extends A {
  @Override
  public String getType() {
    return "TYPE_B";
  }
}

class C extends A {
  @Override
  public String getType() {
    return "TYPE_C";
  }
}
```
So if I run next code:
```
C c = dslJson.deserialize(A.class, "{\"i\":2,\"type\":\"TYPE_C\"}".getBytes());
```
I want to get the instance of the `C` class.

**Comment by zapov** [comment]
Will this work: https://github.com/ngs-doo/dsl-json/blob/master/tests-java8/src/test/java/com/dslplatform/json/InterfaceTest.java#L39

**Comment by zapov** [comment]
It's hardcoded for now

**Comment by zapov** [comment]
You should be able to write some code to do it manually though. Write something along the lines what gets generated.
I can look into adding such an example later if you get stuck

**Comment by ma1uta** [comment]
I tried to write a custom ObjectReader but didn't find manuals how doing this. May be there are some examples?

**Comment by zapov** [comment]
I'll look if there is something which can be done for v1.8.3

**Comment by zapov** [comment]
There is now relevant example here: https://github.com/ngs-doo/dsl-json/tree/master/examples/Polymorphism

**Comment by ma1uta** [comment]
Thanks!

I'll close this issue because there is a deserializer discriminator available.
I am also using the dsl/json library in my projects.
